// Code generated by protoc-gen-go. DO NOT EDIT.
// source: cmd.proto

/*
Package resources is a generated protocol buffer package.

It is generated from these files:
	cmd.proto
	resources.proto

It has these top-level messages:
	ResourceCmdConfig
	CmdConfig
	ResourceSpec
	Query
	Resource
	StringDetail
	BoolDetail
	Int64Detail
	ResourceList
*/
package resources

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Operation int32

const (
	Operation_create Operation = 0
	Operation_get    Operation = 1
	Operation_list   Operation = 2
	Operation_update Operation = 3
	Operation_patch  Operation = 4
	Operation_delete Operation = 5
	Operation_apply  Operation = 6
)

var Operation_name = map[int32]string{
	0: "create",
	1: "get",
	2: "list",
	3: "update",
	4: "patch",
	5: "delete",
	6: "apply",
}
var Operation_value = map[string]int32{
	"create": 0,
	"get":    1,
	"list":   2,
	"update": 3,
	"patch":  4,
	"delete": 5,
	"apply":  6,
}

func (x Operation) Enum() *Operation {
	p := new(Operation)
	*p = x
	return p
}
func (x Operation) String() string {
	return proto.EnumName(Operation_name, int32(x))
}
func (x *Operation) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Operation_value, data, "Operation")
	if err != nil {
		return err
	}
	*x = Operation(value)
	return nil
}
func (Operation) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type ResourceCmdConfig struct {
	Resources        []*CmdConfig `protobuf:"bytes,1,rep,name=Resources" json:"Resources,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *ResourceCmdConfig) Reset()                    { *m = ResourceCmdConfig{} }
func (m *ResourceCmdConfig) String() string            { return proto.CompactTextString(m) }
func (*ResourceCmdConfig) ProtoMessage()               {}
func (*ResourceCmdConfig) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ResourceCmdConfig) GetResources() []*CmdConfig {
	if m != nil {
		return m.Resources
	}
	return nil
}

type CmdConfig struct {
	Name                *string       `protobuf:"bytes,1,req,name=Name" json:"Name,omitempty"`
	Usage               *string       `protobuf:"bytes,2,req,name=Usage" json:"Usage,omitempty"`
	ShortDescription    *string       `protobuf:"bytes,3,req,name=ShortDescription" json:"ShortDescription,omitempty"`
	LongDescription     *string       `protobuf:"bytes,4,req,name=LongDescription" json:"LongDescription,omitempty"`
	SupportedOperations []Operation   `protobuf:"varint,5,rep,name=SupportedOperations,enum=resources.Operation" json:"SupportedOperations,omitempty"`
	Spec                *ResourceSpec `protobuf:"bytes,6,req,name=Spec" json:"Spec,omitempty"`
	XXX_unrecognized    []byte        `json:"-"`
}

func (m *CmdConfig) Reset()                    { *m = CmdConfig{} }
func (m *CmdConfig) String() string            { return proto.CompactTextString(m) }
func (*CmdConfig) ProtoMessage()               {}
func (*CmdConfig) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *CmdConfig) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *CmdConfig) GetUsage() string {
	if m != nil && m.Usage != nil {
		return *m.Usage
	}
	return ""
}

func (m *CmdConfig) GetShortDescription() string {
	if m != nil && m.ShortDescription != nil {
		return *m.ShortDescription
	}
	return ""
}

func (m *CmdConfig) GetLongDescription() string {
	if m != nil && m.LongDescription != nil {
		return *m.LongDescription
	}
	return ""
}

func (m *CmdConfig) GetSupportedOperations() []Operation {
	if m != nil {
		return m.SupportedOperations
	}
	return nil
}

func (m *CmdConfig) GetSpec() *ResourceSpec {
	if m != nil {
		return m.Spec
	}
	return nil
}

type ResourceSpec struct {
	StringOptions    []*StringDetail `protobuf:"bytes,2,rep,name=StringOptions" json:"StringOptions,omitempty"`
	BoolOptions      []*BoolDetail   `protobuf:"bytes,3,rep,name=BoolOptions" json:"BoolOptions,omitempty"`
	Int64Options     []*Int64Detail  `protobuf:"bytes,4,rep,name=Int64Options" json:"Int64Options,omitempty"`
	XXX_unrecognized []byte          `json:"-"`
}

func (m *ResourceSpec) Reset()                    { *m = ResourceSpec{} }
func (m *ResourceSpec) String() string            { return proto.CompactTextString(m) }
func (*ResourceSpec) ProtoMessage()               {}
func (*ResourceSpec) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ResourceSpec) GetStringOptions() []*StringDetail {
	if m != nil {
		return m.StringOptions
	}
	return nil
}

func (m *ResourceSpec) GetBoolOptions() []*BoolDetail {
	if m != nil {
		return m.BoolOptions
	}
	return nil
}

func (m *ResourceSpec) GetInt64Options() []*Int64Detail {
	if m != nil {
		return m.Int64Options
	}
	return nil
}

func init() {
	proto.RegisterType((*ResourceCmdConfig)(nil), "resources.ResourceCmdConfig")
	proto.RegisterType((*CmdConfig)(nil), "resources.CmdConfig")
	proto.RegisterType((*ResourceSpec)(nil), "resources.ResourceSpec")
	proto.RegisterEnum("resources.Operation", Operation_name, Operation_value)
}

func init() { proto.RegisterFile("cmd.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 356 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0x4f, 0x4b, 0xf3, 0x40,
	0x10, 0xc6, 0xdf, 0xfc, 0xeb, 0x6b, 0xa6, 0xd5, 0xc6, 0xb1, 0x6a, 0xf0, 0x14, 0x7a, 0x0a, 0x15,
	0x7a, 0x28, 0xa2, 0x20, 0x78, 0xb1, 0x45, 0x11, 0xc4, 0x42, 0x82, 0xe0, 0x35, 0x24, 0x63, 0x1a,
	0x48, 0xb3, 0xcb, 0x66, 0x7b, 0xf0, 0xe6, 0x67, 0xf3, 0x93, 0x49, 0x36, 0x4d, 0x9a, 0xaa, 0xb7,
	0xc9, 0xf3, 0xfc, 0x7e, 0x13, 0x66, 0xc1, 0x8e, 0xd7, 0xc9, 0x94, 0x0b, 0x26, 0x19, 0xda, 0x82,
	0x4a, 0xb6, 0x11, 0x31, 0x95, 0x17, 0xc3, 0x76, 0xac, 0xbb, 0xf1, 0x23, 0x1c, 0x07, 0xdb, 0x68,
	0xbe, 0x4e, 0xe6, 0xac, 0x78, 0xcf, 0x52, 0x9c, 0x81, 0xdd, 0x84, 0xa5, 0xab, 0x79, 0x86, 0xdf,
	0x9f, 0x8d, 0xa6, 0x3b, 0xb3, 0x05, 0x83, 0x1d, 0x36, 0xfe, 0xd4, 0xc1, 0xde, 0x6d, 0x40, 0x30,
	0x5f, 0xa2, 0x35, 0xb9, 0x9a, 0xa7, 0xfb, 0x76, 0xa0, 0x66, 0x1c, 0x81, 0xf5, 0x5a, 0x46, 0x29,
	0xb9, 0xba, 0x0a, 0xeb, 0x0f, 0x9c, 0x80, 0x13, 0xae, 0x98, 0x90, 0x0b, 0x2a, 0x63, 0x91, 0x71,
	0x99, 0xb1, 0xc2, 0x35, 0x14, 0xf0, 0x2b, 0x47, 0x1f, 0x86, 0xcf, 0xac, 0x48, 0xbb, 0xa8, 0xa9,
	0xd0, 0x9f, 0x31, 0x3e, 0xc0, 0x49, 0xb8, 0xe1, 0x9c, 0x09, 0x49, 0xc9, 0x92, 0x93, 0x88, 0xaa,
	0xb4, 0x74, 0x2d, 0xcf, 0xf0, 0x8f, 0xf6, 0x6e, 0x69, 0xcb, 0xe0, 0x2f, 0x01, 0x2f, 0xc1, 0x0c,
	0x39, 0xc5, 0x6e, 0xcf, 0xd3, 0xfd, 0xfe, 0xec, 0xbc, 0x23, 0x36, 0x97, 0x57, 0x75, 0xa0, 0xa0,
	0xf1, 0x97, 0x06, 0x83, 0x6e, 0x8c, 0x77, 0x70, 0x18, 0x4a, 0x91, 0x15, 0xe9, 0x92, 0xd7, 0xff,
	0xd7, 0xd5, 0x5b, 0x76, 0xd7, 0xd4, 0xfd, 0x82, 0x64, 0x94, 0xe5, 0xc1, 0x3e, 0x8d, 0x37, 0xd0,
	0xbf, 0x67, 0x2c, 0x6f, 0x64, 0x43, 0xc9, 0xa7, 0x1d, 0xb9, 0x6a, 0xb7, 0x6a, 0x97, 0xc4, 0x5b,
	0x18, 0x3c, 0x15, 0xf2, 0xfa, 0xaa, 0x31, 0x4d, 0x65, 0x9e, 0x75, 0x4c, 0x55, 0x6f, 0xd5, 0x3d,
	0x76, 0xf2, 0x06, 0x76, 0x7b, 0x3f, 0x02, 0xf4, 0x62, 0x41, 0x91, 0x24, 0xe7, 0x1f, 0xfe, 0x07,
	0x23, 0x25, 0xe9, 0x68, 0x78, 0x00, 0x66, 0x9e, 0x95, 0xd2, 0xd1, 0xab, 0x7a, 0xc3, 0x93, 0xaa,
	0x36, 0xd0, 0x06, 0x8b, 0x47, 0x32, 0x5e, 0x39, 0x66, 0x15, 0x27, 0x94, 0x93, 0x24, 0xc7, 0xaa,
	0xe2, 0x88, 0xf3, 0xfc, 0xc3, 0xe9, 0x7d, 0x07, 0x00, 0x00, 0xff, 0xff, 0xcd, 0xd8, 0xe8, 0xaa,
	0x92, 0x02, 0x00, 0x00,
}
