// Code generated by protoc-gen-go. DO NOT EDIT.
// source: resources.proto

package resources

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/any"
import google_protobuf1 "github.com/golang/protobuf/ptypes/empty"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type Query struct {
	Query string `protobuf:"bytes,1,opt,name=Query" json:"Query,omitempty"`
	Type  string `protobuf:"bytes,2,opt,name=Type" json:"Type,omitempty"`
}

func (m *Query) Reset()                    { *m = Query{} }
func (m *Query) String() string            { return proto.CompactTextString(m) }
func (*Query) ProtoMessage()               {}
func (*Query) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

func (m *Query) GetQuery() string {
	if m != nil {
		return m.Query
	}
	return ""
}

func (m *Query) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

type Resource struct {
	Id      string                 `protobuf:"bytes,1,opt,name=Id" json:"Id,omitempty"`
	Type    string                 `protobuf:"bytes,2,opt,name=Type" json:"Type,omitempty"`
	Details []*google_protobuf.Any `protobuf:"bytes,3,rep,name=Details" json:"Details,omitempty"`
}

func (m *Resource) Reset()                    { *m = Resource{} }
func (m *Resource) String() string            { return proto.CompactTextString(m) }
func (*Resource) ProtoMessage()               {}
func (*Resource) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

func (m *Resource) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Resource) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Resource) GetDetails() []*google_protobuf.Any {
	if m != nil {
		return m.Details
	}
	return nil
}

type StringDetail struct {
	Name           string `protobuf:"bytes,1,opt,name=Name" json:"Name,omitempty"`
	Value          string `protobuf:"bytes,2,opt,name=Value" json:"Value,omitempty"`
	Required       bool   `protobuf:"varint,3,opt,name=Required" json:"Required,omitempty"`
	Description    string `protobuf:"bytes,4,opt,name=Description" json:"Description,omitempty"`
	Default        string `protobuf:"bytes,5,opt,name=Default" json:"Default,omitempty"`
	IsSecondaryKey bool   `protobuf:"varint,6,opt,name=IsSecondaryKey" json:"IsSecondaryKey,omitempty"`
}

func (m *StringDetail) Reset()                    { *m = StringDetail{} }
func (m *StringDetail) String() string            { return proto.CompactTextString(m) }
func (*StringDetail) ProtoMessage()               {}
func (*StringDetail) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{2} }

func (m *StringDetail) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *StringDetail) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *StringDetail) GetRequired() bool {
	if m != nil {
		return m.Required
	}
	return false
}

func (m *StringDetail) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *StringDetail) GetDefault() string {
	if m != nil {
		return m.Default
	}
	return ""
}

func (m *StringDetail) GetIsSecondaryKey() bool {
	if m != nil {
		return m.IsSecondaryKey
	}
	return false
}

type BoolDetail struct {
	Name           string `protobuf:"bytes,1,opt,name=Name" json:"Name,omitempty"`
	Value          bool   `protobuf:"varint,2,opt,name=Value" json:"Value,omitempty"`
	Required       bool   `protobuf:"varint,3,opt,name=Required" json:"Required,omitempty"`
	Description    string `protobuf:"bytes,4,opt,name=Description" json:"Description,omitempty"`
	Default        bool   `protobuf:"varint,5,opt,name=Default" json:"Default,omitempty"`
	IsSecondaryKey bool   `protobuf:"varint,6,opt,name=IsSecondaryKey" json:"IsSecondaryKey,omitempty"`
}

func (m *BoolDetail) Reset()                    { *m = BoolDetail{} }
func (m *BoolDetail) String() string            { return proto.CompactTextString(m) }
func (*BoolDetail) ProtoMessage()               {}
func (*BoolDetail) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{3} }

func (m *BoolDetail) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *BoolDetail) GetValue() bool {
	if m != nil {
		return m.Value
	}
	return false
}

func (m *BoolDetail) GetRequired() bool {
	if m != nil {
		return m.Required
	}
	return false
}

func (m *BoolDetail) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *BoolDetail) GetDefault() bool {
	if m != nil {
		return m.Default
	}
	return false
}

func (m *BoolDetail) GetIsSecondaryKey() bool {
	if m != nil {
		return m.IsSecondaryKey
	}
	return false
}

type Int64Detail struct {
	Name           string `protobuf:"bytes,1,opt,name=Name" json:"Name,omitempty"`
	Value          int64  `protobuf:"varint,2,opt,name=Value" json:"Value,omitempty"`
	Required       bool   `protobuf:"varint,3,opt,name=Required" json:"Required,omitempty"`
	Description    string `protobuf:"bytes,4,opt,name=Description" json:"Description,omitempty"`
	Default        int64  `protobuf:"varint,5,opt,name=Default" json:"Default,omitempty"`
	IsSecondaryKey bool   `protobuf:"varint,6,opt,name=IsSecondaryKey" json:"IsSecondaryKey,omitempty"`
}

func (m *Int64Detail) Reset()                    { *m = Int64Detail{} }
func (m *Int64Detail) String() string            { return proto.CompactTextString(m) }
func (*Int64Detail) ProtoMessage()               {}
func (*Int64Detail) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{4} }

func (m *Int64Detail) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Int64Detail) GetValue() int64 {
	if m != nil {
		return m.Value
	}
	return 0
}

func (m *Int64Detail) GetRequired() bool {
	if m != nil {
		return m.Required
	}
	return false
}

func (m *Int64Detail) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Int64Detail) GetDefault() int64 {
	if m != nil {
		return m.Default
	}
	return 0
}

func (m *Int64Detail) GetIsSecondaryKey() bool {
	if m != nil {
		return m.IsSecondaryKey
	}
	return false
}

type ResourceList struct {
	Results []*Resource `protobuf:"bytes,1,rep,name=Results" json:"Results,omitempty"`
}

func (m *ResourceList) Reset()                    { *m = ResourceList{} }
func (m *ResourceList) String() string            { return proto.CompactTextString(m) }
func (*ResourceList) ProtoMessage()               {}
func (*ResourceList) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{5} }

func (m *ResourceList) GetResults() []*Resource {
	if m != nil {
		return m.Results
	}
	return nil
}

func init() {
	proto.RegisterType((*Query)(nil), "resources.Query")
	proto.RegisterType((*Resource)(nil), "resources.Resource")
	proto.RegisterType((*StringDetail)(nil), "resources.StringDetail")
	proto.RegisterType((*BoolDetail)(nil), "resources.BoolDetail")
	proto.RegisterType((*Int64Detail)(nil), "resources.Int64Detail")
	proto.RegisterType((*ResourceList)(nil), "resources.ResourceList")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for ResourceEndpoint service

type ResourceEndpointClient interface {
	GetResource(ctx context.Context, in *Resource, opts ...grpc.CallOption) (*Resource, error)
	ListResources(ctx context.Context, in *Query, opts ...grpc.CallOption) (*ResourceList, error)
	CreateResource(ctx context.Context, in *Resource, opts ...grpc.CallOption) (*Resource, error)
	UpdateResource(ctx context.Context, in *Resource, opts ...grpc.CallOption) (*google_protobuf1.Empty, error)
	DeleteResource(ctx context.Context, in *Resource, opts ...grpc.CallOption) (*google_protobuf1.Empty, error)
}

type resourceEndpointClient struct {
	cc *grpc.ClientConn
}

func NewResourceEndpointClient(cc *grpc.ClientConn) ResourceEndpointClient {
	return &resourceEndpointClient{cc}
}

func (c *resourceEndpointClient) GetResource(ctx context.Context, in *Resource, opts ...grpc.CallOption) (*Resource, error) {
	out := new(Resource)
	err := grpc.Invoke(ctx, "/resources.ResourceEndpoint/GetResource", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resourceEndpointClient) ListResources(ctx context.Context, in *Query, opts ...grpc.CallOption) (*ResourceList, error) {
	out := new(ResourceList)
	err := grpc.Invoke(ctx, "/resources.ResourceEndpoint/ListResources", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resourceEndpointClient) CreateResource(ctx context.Context, in *Resource, opts ...grpc.CallOption) (*Resource, error) {
	out := new(Resource)
	err := grpc.Invoke(ctx, "/resources.ResourceEndpoint/CreateResource", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resourceEndpointClient) UpdateResource(ctx context.Context, in *Resource, opts ...grpc.CallOption) (*google_protobuf1.Empty, error) {
	out := new(google_protobuf1.Empty)
	err := grpc.Invoke(ctx, "/resources.ResourceEndpoint/UpdateResource", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resourceEndpointClient) DeleteResource(ctx context.Context, in *Resource, opts ...grpc.CallOption) (*google_protobuf1.Empty, error) {
	out := new(google_protobuf1.Empty)
	err := grpc.Invoke(ctx, "/resources.ResourceEndpoint/DeleteResource", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for ResourceEndpoint service

type ResourceEndpointServer interface {
	GetResource(context.Context, *Resource) (*Resource, error)
	ListResources(context.Context, *Query) (*ResourceList, error)
	CreateResource(context.Context, *Resource) (*Resource, error)
	UpdateResource(context.Context, *Resource) (*google_protobuf1.Empty, error)
	DeleteResource(context.Context, *Resource) (*google_protobuf1.Empty, error)
}

func RegisterResourceEndpointServer(s *grpc.Server, srv ResourceEndpointServer) {
	s.RegisterService(&_ResourceEndpoint_serviceDesc, srv)
}

func _ResourceEndpoint_GetResource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Resource)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourceEndpointServer).GetResource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/resources.ResourceEndpoint/GetResource",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourceEndpointServer).GetResource(ctx, req.(*Resource))
	}
	return interceptor(ctx, in, info, handler)
}

func _ResourceEndpoint_ListResources_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Query)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourceEndpointServer).ListResources(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/resources.ResourceEndpoint/ListResources",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourceEndpointServer).ListResources(ctx, req.(*Query))
	}
	return interceptor(ctx, in, info, handler)
}

func _ResourceEndpoint_CreateResource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Resource)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourceEndpointServer).CreateResource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/resources.ResourceEndpoint/CreateResource",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourceEndpointServer).CreateResource(ctx, req.(*Resource))
	}
	return interceptor(ctx, in, info, handler)
}

func _ResourceEndpoint_UpdateResource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Resource)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourceEndpointServer).UpdateResource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/resources.ResourceEndpoint/UpdateResource",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourceEndpointServer).UpdateResource(ctx, req.(*Resource))
	}
	return interceptor(ctx, in, info, handler)
}

func _ResourceEndpoint_DeleteResource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Resource)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourceEndpointServer).DeleteResource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/resources.ResourceEndpoint/DeleteResource",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourceEndpointServer).DeleteResource(ctx, req.(*Resource))
	}
	return interceptor(ctx, in, info, handler)
}

var _ResourceEndpoint_serviceDesc = grpc.ServiceDesc{
	ServiceName: "resources.ResourceEndpoint",
	HandlerType: (*ResourceEndpointServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetResource",
			Handler:    _ResourceEndpoint_GetResource_Handler,
		},
		{
			MethodName: "ListResources",
			Handler:    _ResourceEndpoint_ListResources_Handler,
		},
		{
			MethodName: "CreateResource",
			Handler:    _ResourceEndpoint_CreateResource_Handler,
		},
		{
			MethodName: "UpdateResource",
			Handler:    _ResourceEndpoint_UpdateResource_Handler,
		},
		{
			MethodName: "DeleteResource",
			Handler:    _ResourceEndpoint_DeleteResource_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "resources.proto",
}

func init() { proto.RegisterFile("resources.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 423 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x94, 0xdf, 0x8a, 0xd3, 0x40,
	0x14, 0xc6, 0x4d, 0xb2, 0x7f, 0xb2, 0x27, 0x6b, 0x5c, 0xc6, 0x45, 0xc7, 0x78, 0x13, 0x72, 0x21,
	0xbd, 0x31, 0x8b, 0xab, 0x08, 0x82, 0x22, 0x6a, 0x17, 0x09, 0x8a, 0x60, 0x56, 0xbd, 0x14, 0xd2,
	0xe6, 0xb4, 0x04, 0xd2, 0x99, 0x38, 0x33, 0xb9, 0xc8, 0x8b, 0xa9, 0xef, 0xe0, 0x4b, 0x49, 0x26,
	0x99, 0x5a, 0x6a, 0x60, 0xdb, 0x42, 0xef, 0x66, 0xbe, 0xf3, 0x7d, 0xe7, 0xfc, 0x2e, 0xe6, 0x0c,
	0xdc, 0x11, 0x28, 0x79, 0x2d, 0xa6, 0x28, 0xe3, 0x4a, 0x70, 0xc5, 0xc9, 0xc9, 0x52, 0x08, 0x1e,
	0xcc, 0x39, 0x9f, 0x97, 0x78, 0xa1, 0x0b, 0x93, 0x7a, 0x76, 0x91, 0xb1, 0xa6, 0x73, 0x05, 0x0f,
	0xd7, 0x4b, 0xb8, 0xa8, 0x54, 0x5f, 0x8c, 0x9e, 0xc0, 0xe1, 0xe7, 0x1a, 0x45, 0x43, 0xce, 0xfb,
	0x03, 0xb5, 0x42, 0x6b, 0x74, 0x92, 0xf6, 0x2a, 0x81, 0x83, 0x2f, 0x4d, 0x85, 0xd4, 0xd6, 0xa2,
	0x3e, 0x47, 0xdf, 0xc1, 0x4d, 0xfb, 0xb9, 0xc4, 0x07, 0x3b, 0xc9, 0xfb, 0x88, 0x9d, 0xe4, 0x43,
	0x7e, 0x12, 0xc3, 0xf1, 0x18, 0x55, 0x56, 0x94, 0x92, 0x3a, 0xa1, 0x33, 0xf2, 0x2e, 0xcf, 0xe3,
	0x8e, 0x28, 0x36, 0x44, 0xf1, 0x1b, 0xd6, 0xa4, 0xc6, 0x14, 0xfd, 0xb6, 0xe0, 0xf4, 0x5a, 0x89,
	0x82, 0xcd, 0x3b, 0xa5, 0x6d, 0xfa, 0x29, 0x5b, 0x60, 0x3f, 0x46, 0x9f, 0x5b, 0xdc, 0x6f, 0x59,
	0x59, 0x9b, 0x49, 0xdd, 0x85, 0x04, 0x2d, 0xda, 0x8f, 0xba, 0x10, 0x98, 0x53, 0x27, 0xb4, 0x46,
	0x6e, 0xba, 0xbc, 0x93, 0x10, 0xbc, 0x31, 0xca, 0xa9, 0x28, 0x2a, 0x55, 0x70, 0x46, 0x0f, 0x74,
	0x6e, 0x55, 0x22, 0xb4, 0x05, 0x9d, 0x65, 0x75, 0xa9, 0xe8, 0xa1, 0xae, 0x9a, 0x2b, 0x79, 0x04,
	0x7e, 0x22, 0xaf, 0x71, 0xca, 0x59, 0x9e, 0x89, 0xe6, 0x03, 0x36, 0xf4, 0x48, 0x77, 0x5f, 0x53,
	0xa3, 0x9f, 0x16, 0xc0, 0x5b, 0xce, 0xcb, 0x4d, 0xc1, 0xdd, 0xbd, 0x80, 0xbb, 0xdb, 0x83, 0xff,
	0xb2, 0xc0, 0x4b, 0x98, 0x7a, 0xfe, 0x6c, 0x53, 0x72, 0x67, 0x2f, 0xe4, 0xce, 0xf6, 0xe4, 0xaf,
	0xe0, 0xd4, 0xbc, 0xc6, 0x8f, 0x85, 0x54, 0xe4, 0x31, 0x1c, 0xa7, 0x28, 0xeb, 0x52, 0x49, 0x6a,
	0xe9, 0xd7, 0x76, 0x37, 0xfe, 0xb7, 0x36, 0xc6, 0x99, 0x1a, 0xcf, 0xe5, 0x1f, 0x1b, 0xce, 0x8c,
	0x7a, 0xc5, 0xf2, 0x8a, 0x17, 0x4c, 0x91, 0x17, 0xe0, 0xbd, 0x47, 0xb5, 0x7c, 0xe4, 0x43, 0x1d,
	0x82, 0x21, 0x31, 0xba, 0x45, 0x5e, 0xc2, 0xed, 0x16, 0xc3, 0x28, 0x92, 0x9c, 0xad, 0xf8, 0xf4,
	0x4e, 0x05, 0xf7, 0x07, 0x92, 0x6d, 0x46, 0xa7, 0xfd, 0x77, 0x02, 0x33, 0x85, 0x3b, 0xcd, 0x7e,
	0x0d, 0xfe, 0xd7, 0x2a, 0xbf, 0x31, 0x7d, 0xef, 0xbf, 0xf5, 0xbb, 0x6a, 0x3f, 0x84, 0xae, 0xc1,
	0x18, 0x4b, 0xdc, 0xb9, 0xc1, 0xe4, 0x48, 0x2b, 0x4f, 0xff, 0x06, 0x00, 0x00, 0xff, 0xff, 0xbf,
	0xa9, 0xa6, 0x87, 0xaa, 0x04, 0x00, 0x00,
}
