// Code generated by protoc-gen-go. DO NOT EDIT.
// source: resources.proto

package resources

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/any"
import google_protobuf1 "github.com/golang/protobuf/ptypes/empty"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type Query struct {
	Query string `protobuf:"bytes,1,opt,name=Query" json:"Query,omitempty"`
	Type  string `protobuf:"bytes,2,opt,name=Type" json:"Type,omitempty"`
}

func (m *Query) Reset()                    { *m = Query{} }
func (m *Query) String() string            { return proto.CompactTextString(m) }
func (*Query) ProtoMessage()               {}
func (*Query) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

func (m *Query) GetQuery() string {
	if m != nil {
		return m.Query
	}
	return ""
}

func (m *Query) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

type Resource struct {
	Id      string                 `protobuf:"bytes,1,opt,name=Id" json:"Id,omitempty"`
	Type    string                 `protobuf:"bytes,2,opt,name=Type" json:"Type,omitempty"`
	Details []*google_protobuf.Any `protobuf:"bytes,3,rep,name=Details" json:"Details,omitempty"`
}

func (m *Resource) Reset()                    { *m = Resource{} }
func (m *Resource) String() string            { return proto.CompactTextString(m) }
func (*Resource) ProtoMessage()               {}
func (*Resource) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

func (m *Resource) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Resource) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Resource) GetDetails() []*google_protobuf.Any {
	if m != nil {
		return m.Details
	}
	return nil
}

type StringDetail struct {
	Name        string `protobuf:"bytes,1,opt,name=Name" json:"Name,omitempty"`
	Value       string `protobuf:"bytes,2,opt,name=Value" json:"Value,omitempty"`
	Required    bool   `protobuf:"varint,3,opt,name=Required" json:"Required,omitempty"`
	Description string `protobuf:"bytes,4,opt,name=Description" json:"Description,omitempty"`
	Default     string `protobuf:"bytes,5,opt,name=Default" json:"Default,omitempty"`
}

func (m *StringDetail) Reset()                    { *m = StringDetail{} }
func (m *StringDetail) String() string            { return proto.CompactTextString(m) }
func (*StringDetail) ProtoMessage()               {}
func (*StringDetail) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{2} }

func (m *StringDetail) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *StringDetail) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *StringDetail) GetRequired() bool {
	if m != nil {
		return m.Required
	}
	return false
}

func (m *StringDetail) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *StringDetail) GetDefault() string {
	if m != nil {
		return m.Default
	}
	return ""
}

type BoolDetail struct {
	Name        string `protobuf:"bytes,1,opt,name=Name" json:"Name,omitempty"`
	Value       bool   `protobuf:"varint,2,opt,name=Value" json:"Value,omitempty"`
	Required    bool   `protobuf:"varint,3,opt,name=Required" json:"Required,omitempty"`
	Description string `protobuf:"bytes,4,opt,name=Description" json:"Description,omitempty"`
	Default     bool   `protobuf:"varint,5,opt,name=Default" json:"Default,omitempty"`
}

func (m *BoolDetail) Reset()                    { *m = BoolDetail{} }
func (m *BoolDetail) String() string            { return proto.CompactTextString(m) }
func (*BoolDetail) ProtoMessage()               {}
func (*BoolDetail) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{3} }

func (m *BoolDetail) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *BoolDetail) GetValue() bool {
	if m != nil {
		return m.Value
	}
	return false
}

func (m *BoolDetail) GetRequired() bool {
	if m != nil {
		return m.Required
	}
	return false
}

func (m *BoolDetail) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *BoolDetail) GetDefault() bool {
	if m != nil {
		return m.Default
	}
	return false
}

type Int64Detail struct {
	Name        string `protobuf:"bytes,1,opt,name=Name" json:"Name,omitempty"`
	Value       int64  `protobuf:"varint,2,opt,name=Value" json:"Value,omitempty"`
	Required    bool   `protobuf:"varint,3,opt,name=Required" json:"Required,omitempty"`
	Description string `protobuf:"bytes,4,opt,name=Description" json:"Description,omitempty"`
	Default     int64  `protobuf:"varint,5,opt,name=Default" json:"Default,omitempty"`
}

func (m *Int64Detail) Reset()                    { *m = Int64Detail{} }
func (m *Int64Detail) String() string            { return proto.CompactTextString(m) }
func (*Int64Detail) ProtoMessage()               {}
func (*Int64Detail) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{4} }

func (m *Int64Detail) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Int64Detail) GetValue() int64 {
	if m != nil {
		return m.Value
	}
	return 0
}

func (m *Int64Detail) GetRequired() bool {
	if m != nil {
		return m.Required
	}
	return false
}

func (m *Int64Detail) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Int64Detail) GetDefault() int64 {
	if m != nil {
		return m.Default
	}
	return 0
}

type ResourceList struct {
	Results []*Resource `protobuf:"bytes,1,rep,name=Results" json:"Results,omitempty"`
}

func (m *ResourceList) Reset()                    { *m = ResourceList{} }
func (m *ResourceList) String() string            { return proto.CompactTextString(m) }
func (*ResourceList) ProtoMessage()               {}
func (*ResourceList) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{5} }

func (m *ResourceList) GetResults() []*Resource {
	if m != nil {
		return m.Results
	}
	return nil
}

func init() {
	proto.RegisterType((*Query)(nil), "resources.Query")
	proto.RegisterType((*Resource)(nil), "resources.Resource")
	proto.RegisterType((*StringDetail)(nil), "resources.StringDetail")
	proto.RegisterType((*BoolDetail)(nil), "resources.BoolDetail")
	proto.RegisterType((*Int64Detail)(nil), "resources.Int64Detail")
	proto.RegisterType((*ResourceList)(nil), "resources.ResourceList")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for ResourceEndpoint service

type ResourceEndpointClient interface {
	GetResource(ctx context.Context, in *Resource, opts ...grpc.CallOption) (*Resource, error)
	ListResources(ctx context.Context, in *Query, opts ...grpc.CallOption) (*ResourceList, error)
	CreateResource(ctx context.Context, in *Resource, opts ...grpc.CallOption) (*Resource, error)
	UpdateResource(ctx context.Context, in *Resource, opts ...grpc.CallOption) (*google_protobuf1.Empty, error)
	DeleteResource(ctx context.Context, in *Resource, opts ...grpc.CallOption) (*google_protobuf1.Empty, error)
}

type resourceEndpointClient struct {
	cc *grpc.ClientConn
}

func NewResourceEndpointClient(cc *grpc.ClientConn) ResourceEndpointClient {
	return &resourceEndpointClient{cc}
}

func (c *resourceEndpointClient) GetResource(ctx context.Context, in *Resource, opts ...grpc.CallOption) (*Resource, error) {
	out := new(Resource)
	err := grpc.Invoke(ctx, "/resources.ResourceEndpoint/GetResource", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resourceEndpointClient) ListResources(ctx context.Context, in *Query, opts ...grpc.CallOption) (*ResourceList, error) {
	out := new(ResourceList)
	err := grpc.Invoke(ctx, "/resources.ResourceEndpoint/ListResources", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resourceEndpointClient) CreateResource(ctx context.Context, in *Resource, opts ...grpc.CallOption) (*Resource, error) {
	out := new(Resource)
	err := grpc.Invoke(ctx, "/resources.ResourceEndpoint/CreateResource", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resourceEndpointClient) UpdateResource(ctx context.Context, in *Resource, opts ...grpc.CallOption) (*google_protobuf1.Empty, error) {
	out := new(google_protobuf1.Empty)
	err := grpc.Invoke(ctx, "/resources.ResourceEndpoint/UpdateResource", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resourceEndpointClient) DeleteResource(ctx context.Context, in *Resource, opts ...grpc.CallOption) (*google_protobuf1.Empty, error) {
	out := new(google_protobuf1.Empty)
	err := grpc.Invoke(ctx, "/resources.ResourceEndpoint/DeleteResource", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for ResourceEndpoint service

type ResourceEndpointServer interface {
	GetResource(context.Context, *Resource) (*Resource, error)
	ListResources(context.Context, *Query) (*ResourceList, error)
	CreateResource(context.Context, *Resource) (*Resource, error)
	UpdateResource(context.Context, *Resource) (*google_protobuf1.Empty, error)
	DeleteResource(context.Context, *Resource) (*google_protobuf1.Empty, error)
}

func RegisterResourceEndpointServer(s *grpc.Server, srv ResourceEndpointServer) {
	s.RegisterService(&_ResourceEndpoint_serviceDesc, srv)
}

func _ResourceEndpoint_GetResource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Resource)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourceEndpointServer).GetResource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/resources.ResourceEndpoint/GetResource",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourceEndpointServer).GetResource(ctx, req.(*Resource))
	}
	return interceptor(ctx, in, info, handler)
}

func _ResourceEndpoint_ListResources_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Query)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourceEndpointServer).ListResources(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/resources.ResourceEndpoint/ListResources",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourceEndpointServer).ListResources(ctx, req.(*Query))
	}
	return interceptor(ctx, in, info, handler)
}

func _ResourceEndpoint_CreateResource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Resource)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourceEndpointServer).CreateResource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/resources.ResourceEndpoint/CreateResource",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourceEndpointServer).CreateResource(ctx, req.(*Resource))
	}
	return interceptor(ctx, in, info, handler)
}

func _ResourceEndpoint_UpdateResource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Resource)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourceEndpointServer).UpdateResource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/resources.ResourceEndpoint/UpdateResource",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourceEndpointServer).UpdateResource(ctx, req.(*Resource))
	}
	return interceptor(ctx, in, info, handler)
}

func _ResourceEndpoint_DeleteResource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Resource)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourceEndpointServer).DeleteResource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/resources.ResourceEndpoint/DeleteResource",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourceEndpointServer).DeleteResource(ctx, req.(*Resource))
	}
	return interceptor(ctx, in, info, handler)
}

var _ResourceEndpoint_serviceDesc = grpc.ServiceDesc{
	ServiceName: "resources.ResourceEndpoint",
	HandlerType: (*ResourceEndpointServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetResource",
			Handler:    _ResourceEndpoint_GetResource_Handler,
		},
		{
			MethodName: "ListResources",
			Handler:    _ResourceEndpoint_ListResources_Handler,
		},
		{
			MethodName: "CreateResource",
			Handler:    _ResourceEndpoint_CreateResource_Handler,
		},
		{
			MethodName: "UpdateResource",
			Handler:    _ResourceEndpoint_UpdateResource_Handler,
		},
		{
			MethodName: "DeleteResource",
			Handler:    _ResourceEndpoint_DeleteResource_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "resources.proto",
}

func init() { proto.RegisterFile("resources.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 401 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x93, 0xdf, 0xaa, 0xd3, 0x40,
	0x10, 0xc6, 0x4d, 0xd2, 0xda, 0x74, 0x52, 0x6b, 0x59, 0x8b, 0xae, 0xf1, 0x26, 0xe4, 0xaa, 0x37,
	0xa6, 0x58, 0x45, 0x10, 0x14, 0x51, 0x5b, 0xa4, 0x20, 0x82, 0xf1, 0xcf, 0xa5, 0x90, 0x36, 0xd3,
	0x12, 0x48, 0xb3, 0x71, 0x77, 0x73, 0x91, 0x97, 0x50, 0xdf, 0xeb, 0xbc, 0xd4, 0x21, 0x9b, 0x6c,
	0x5b, 0xce, 0x09, 0x9c, 0x52, 0xe8, 0xdd, 0xce, 0x37, 0xdf, 0x37, 0xf3, 0x83, 0x4c, 0xe0, 0x21,
	0x47, 0xc1, 0x0a, 0xbe, 0x46, 0x11, 0xe4, 0x9c, 0x49, 0x46, 0xfa, 0x7b, 0xc1, 0x7d, 0xba, 0x65,
	0x6c, 0x9b, 0xe2, 0x54, 0x35, 0x56, 0xc5, 0x66, 0x1a, 0x65, 0x65, 0xed, 0x72, 0x9f, 0xdd, 0x6c,
	0xe1, 0x2e, 0x97, 0x4d, 0xd3, 0x7f, 0x01, 0xdd, 0x6f, 0x05, 0xf2, 0x92, 0x8c, 0x9b, 0x07, 0x35,
	0x3c, 0x63, 0xd2, 0x0f, 0x1b, 0x95, 0x40, 0xe7, 0x47, 0x99, 0x23, 0x35, 0x95, 0xa8, 0xde, 0xfe,
	0x6f, 0xb0, 0xc3, 0x66, 0x2f, 0x19, 0x82, 0xb9, 0x8c, 0x9b, 0x88, 0xb9, 0x8c, 0xdb, 0xfc, 0x24,
	0x80, 0xde, 0x1c, 0x65, 0x94, 0xa4, 0x82, 0x5a, 0x9e, 0x35, 0x71, 0x66, 0xe3, 0xa0, 0x26, 0x0a,
	0x34, 0x51, 0xf0, 0x21, 0x2b, 0x43, 0x6d, 0xf2, 0xff, 0x1b, 0x30, 0xf8, 0x2e, 0x79, 0x92, 0x6d,
	0x6b, 0xa5, 0x1a, 0xfa, 0x35, 0xda, 0x61, 0xb3, 0x46, 0xbd, 0x2b, 0xdc, 0x5f, 0x51, 0x5a, 0xe8,
	0x4d, 0x75, 0x41, 0xdc, 0x0a, 0xed, 0x4f, 0x91, 0x70, 0x8c, 0xa9, 0xe5, 0x19, 0x13, 0x3b, 0xdc,
	0xd7, 0xc4, 0x03, 0x67, 0x8e, 0x62, 0xcd, 0x93, 0x5c, 0x26, 0x2c, 0xa3, 0x1d, 0x95, 0x3b, 0x96,
	0x08, 0xad, 0x40, 0x37, 0x51, 0x91, 0x4a, 0xda, 0x55, 0x5d, 0x5d, 0xfa, 0x7f, 0x0d, 0x80, 0x8f,
	0x8c, 0xa5, 0xa7, 0x02, 0xd9, 0x17, 0x01, 0xb2, 0x0f, 0x40, 0xff, 0x0c, 0x70, 0x96, 0x99, 0x7c,
	0xfd, 0xea, 0x54, 0x22, 0xeb, 0x22, 0x44, 0xd6, 0x81, 0xe8, 0x1d, 0x0c, 0xf4, 0x55, 0x7c, 0x49,
	0x84, 0x24, 0xcf, 0xa1, 0x17, 0xa2, 0x28, 0x52, 0x29, 0xa8, 0xa1, 0xbe, 0xfa, 0xa3, 0xe0, 0x70,
	0xbe, 0xda, 0x19, 0x6a, 0xcf, 0xec, 0xca, 0x84, 0x91, 0x56, 0x17, 0x59, 0x9c, 0xb3, 0x24, 0x93,
	0xe4, 0x0d, 0x38, 0x9f, 0x51, 0xee, 0x8f, 0xad, 0x6d, 0x82, 0xdb, 0x26, 0xfa, 0xf7, 0xc8, 0x5b,
	0x78, 0x50, 0x61, 0x68, 0x45, 0x90, 0xd1, 0x91, 0x4f, 0xdd, 0xb6, 0xfb, 0xa4, 0x25, 0x59, 0x65,
	0x54, 0x7a, 0xf8, 0x89, 0x63, 0x24, 0xf1, 0xac, 0xdd, 0xef, 0x61, 0xf8, 0x33, 0x8f, 0xef, 0x4c,
	0x3f, 0xbe, 0xf5, 0x1b, 0x2c, 0xaa, 0x1f, 0xb3, 0x1e, 0x30, 0xc7, 0x14, 0xcf, 0x1e, 0xb0, 0xba,
	0xaf, 0x94, 0x97, 0xd7, 0x01, 0x00, 0x00, 0xff, 0xff, 0xd7, 0x97, 0x5f, 0x3d, 0x32, 0x04, 0x00,
	0x00,
}
