// Code generated by protoc-gen-go. DO NOT EDIT.
// source: cmd.proto

package leveler

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type CmdCongig struct {
	Name             *string      `protobuf:"bytes,1,req,name=Name" json:"Name,omitempty"`
	Usage            *string      `protobuf:"bytes,2,req,name=Usage" json:"Usage,omitempty"`
	ShortDescription *string      `protobuf:"bytes,3,req,name=ShortDescription" json:"ShortDescription,omitempty"`
	LongDescription  *string      `protobuf:"bytes,4,req,name=LongDescription" json:"LongDescription,omitempty"`
	Options          []*CmdOption `protobuf:"bytes,5,rep,name=Options" json:"Options,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *CmdCongig) Reset()                    { *m = CmdCongig{} }
func (m *CmdCongig) String() string            { return proto.CompactTextString(m) }
func (*CmdCongig) ProtoMessage()               {}
func (*CmdCongig) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

func (m *CmdCongig) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *CmdCongig) GetUsage() string {
	if m != nil && m.Usage != nil {
		return *m.Usage
	}
	return ""
}

func (m *CmdCongig) GetShortDescription() string {
	if m != nil && m.ShortDescription != nil {
		return *m.ShortDescription
	}
	return ""
}

func (m *CmdCongig) GetLongDescription() string {
	if m != nil && m.LongDescription != nil {
		return *m.LongDescription
	}
	return ""
}

func (m *CmdCongig) GetOptions() []*CmdOption {
	if m != nil {
		return m.Options
	}
	return nil
}

type CmdOption struct {
	Name             *string `protobuf:"bytes,1,req,name=Name" json:"Name,omitempty"`
	ShortName        *string `protobuf:"bytes,2,req,name=ShortName" json:"ShortName,omitempty"`
	Required         *bool   `protobuf:"varint,3,req,name=Required" json:"Required,omitempty"`
	Type             *string `protobuf:"bytes,4,req,name=Type" json:"Type,omitempty"`
	Description      *string `protobuf:"bytes,5,req,name=Description" json:"Description,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CmdOption) Reset()                    { *m = CmdOption{} }
func (m *CmdOption) String() string            { return proto.CompactTextString(m) }
func (*CmdOption) ProtoMessage()               {}
func (*CmdOption) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

func (m *CmdOption) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *CmdOption) GetShortName() string {
	if m != nil && m.ShortName != nil {
		return *m.ShortName
	}
	return ""
}

func (m *CmdOption) GetRequired() bool {
	if m != nil && m.Required != nil {
		return *m.Required
	}
	return false
}

func (m *CmdOption) GetType() string {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return ""
}

func (m *CmdOption) GetDescription() string {
	if m != nil && m.Description != nil {
		return *m.Description
	}
	return ""
}

func init() {
	proto.RegisterType((*CmdCongig)(nil), "leveler.CmdCongig")
	proto.RegisterType((*CmdOption)(nil), "leveler.CmdOption")
}

func init() { proto.RegisterFile("cmd.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 218 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4c, 0xce, 0x4d, 0xd1,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xcf, 0x49, 0x2d, 0x4b, 0xcd, 0x49, 0x2d, 0x52, 0xda,
	0xc9, 0xc8, 0xc5, 0xe9, 0x9c, 0x9b, 0xe2, 0x9c, 0x9f, 0x97, 0x9e, 0x99, 0x2e, 0x24, 0xc4, 0xc5,
	0xe2, 0x97, 0x98, 0x9b, 0x2a, 0xc1, 0xa8, 0xc0, 0xa4, 0xc1, 0x19, 0x04, 0x66, 0x0b, 0x89, 0x70,
	0xb1, 0x86, 0x16, 0x27, 0xa6, 0xa7, 0x4a, 0x30, 0x81, 0x05, 0x21, 0x1c, 0x21, 0x2d, 0x2e, 0x81,
	0xe0, 0x8c, 0xfc, 0xa2, 0x12, 0x97, 0xd4, 0xe2, 0xe4, 0xa2, 0xcc, 0x82, 0x92, 0xcc, 0xfc, 0x3c,
	0x09, 0x66, 0xb0, 0x02, 0x0c, 0x71, 0x21, 0x0d, 0x2e, 0x7e, 0x9f, 0xfc, 0xbc, 0x74, 0x64, 0xa5,
	0x2c, 0x60, 0xa5, 0xe8, 0xc2, 0x42, 0x3a, 0x5c, 0xec, 0xfe, 0x60, 0x56, 0xb1, 0x04, 0xab, 0x02,
	0xb3, 0x06, 0xb7, 0x91, 0x90, 0x1e, 0xd4, 0xa1, 0x7a, 0xce, 0xb9, 0x29, 0x10, 0xa9, 0x20, 0x98,
	0x12, 0xa5, 0x7e, 0x88, 0xdb, 0x21, 0x5c, 0xac, 0x6e, 0x97, 0xe1, 0xe2, 0x04, 0xbb, 0x06, 0x2c,
	0x01, 0x71, 0x3f, 0x42, 0x40, 0x48, 0x8a, 0x8b, 0x23, 0x28, 0xb5, 0xb0, 0x34, 0xb3, 0x28, 0x35,
	0x05, 0xec, 0x76, 0x8e, 0x20, 0x38, 0x1f, 0x64, 0x5a, 0x48, 0x65, 0x41, 0x2a, 0xd4, 0xa1, 0x60,
	0xb6, 0x90, 0x02, 0x17, 0x37, 0xb2, 0x1f, 0x58, 0xc1, 0x52, 0xc8, 0x42, 0x80, 0x00, 0x00, 0x00,
	0xff, 0xff, 0xd8, 0x0a, 0x0f, 0x20, 0x62, 0x01, 0x00, 0x00,
}
