// Code generated by protoc-gen-go. DO NOT EDIT.
// source: integration.proto

package server

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type Language int32

const (
	Language_java   Language = 0
	Language_golang Language = 1
	Language_python Language = 2
)

var Language_name = map[int32]string{
	0: "java",
	1: "golang",
	2: "python",
}
var Language_value = map[string]int32{
	"java":   0,
	"golang": 1,
	"python": 2,
}

func (x Language) String() string {
	return proto.EnumName(Language_name, int32(x))
}
func (Language) EnumDescriptor() ([]byte, []int) { return fileDescriptor2, []int{0} }

type BuildTool int32

const (
	BuildTool_mvn    BuildTool = 0
	BuildTool_gradle BuildTool = 1
)

var BuildTool_name = map[int32]string{
	0: "mvn",
	1: "gradle",
}
var BuildTool_value = map[string]int32{
	"mvn":    0,
	"gradle": 1,
}

func (x BuildTool) String() string {
	return proto.EnumName(BuildTool_name, int32(x))
}
func (BuildTool) EnumDescriptor() ([]byte, []int) { return fileDescriptor2, []int{1} }

type Integration struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	// Types that are valid to be assigned to Config:
	//	*Integration_Bitbucket
	//	*Integration_Github
	//	*Integration_Aws
	//	*Integration_Nexus
	//	*Integration_Slack
	Config isIntegration_Config `protobuf_oneof:"config"`
}

func (m *Integration) Reset()                    { *m = Integration{} }
func (m *Integration) String() string            { return proto.CompactTextString(m) }
func (*Integration) ProtoMessage()               {}
func (*Integration) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{0} }

type isIntegration_Config interface {
	isIntegration_Config()
}

type Integration_Bitbucket struct {
	Bitbucket *BitbucketAccessConfig `protobuf:"bytes,4,opt,name=bitbucket,oneof"`
}
type Integration_Github struct {
	Github *GithubAccessConfig `protobuf:"bytes,5,opt,name=github,oneof"`
}
type Integration_Aws struct {
	Aws *AWSAccessConfig `protobuf:"bytes,6,opt,name=aws,oneof"`
}
type Integration_Nexus struct {
	Nexus *NexusAccessConfig `protobuf:"bytes,7,opt,name=nexus,oneof"`
}
type Integration_Slack struct {
	Slack *SlackAccessConfig `protobuf:"bytes,8,opt,name=slack,oneof"`
}

func (*Integration_Bitbucket) isIntegration_Config() {}
func (*Integration_Github) isIntegration_Config()    {}
func (*Integration_Aws) isIntegration_Config()       {}
func (*Integration_Nexus) isIntegration_Config()     {}
func (*Integration_Slack) isIntegration_Config()     {}

func (m *Integration) GetConfig() isIntegration_Config {
	if m != nil {
		return m.Config
	}
	return nil
}

func (m *Integration) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Integration) GetBitbucket() *BitbucketAccessConfig {
	if x, ok := m.GetConfig().(*Integration_Bitbucket); ok {
		return x.Bitbucket
	}
	return nil
}

func (m *Integration) GetGithub() *GithubAccessConfig {
	if x, ok := m.GetConfig().(*Integration_Github); ok {
		return x.Github
	}
	return nil
}

func (m *Integration) GetAws() *AWSAccessConfig {
	if x, ok := m.GetConfig().(*Integration_Aws); ok {
		return x.Aws
	}
	return nil
}

func (m *Integration) GetNexus() *NexusAccessConfig {
	if x, ok := m.GetConfig().(*Integration_Nexus); ok {
		return x.Nexus
	}
	return nil
}

func (m *Integration) GetSlack() *SlackAccessConfig {
	if x, ok := m.GetConfig().(*Integration_Slack); ok {
		return x.Slack
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Integration) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Integration_OneofMarshaler, _Integration_OneofUnmarshaler, _Integration_OneofSizer, []interface{}{
		(*Integration_Bitbucket)(nil),
		(*Integration_Github)(nil),
		(*Integration_Aws)(nil),
		(*Integration_Nexus)(nil),
		(*Integration_Slack)(nil),
	}
}

func _Integration_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Integration)
	// config
	switch x := m.Config.(type) {
	case *Integration_Bitbucket:
		b.EncodeVarint(4<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Bitbucket); err != nil {
			return err
		}
	case *Integration_Github:
		b.EncodeVarint(5<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Github); err != nil {
			return err
		}
	case *Integration_Aws:
		b.EncodeVarint(6<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Aws); err != nil {
			return err
		}
	case *Integration_Nexus:
		b.EncodeVarint(7<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Nexus); err != nil {
			return err
		}
	case *Integration_Slack:
		b.EncodeVarint(8<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Slack); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("Integration.Config has unexpected type %T", x)
	}
	return nil
}

func _Integration_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Integration)
	switch tag {
	case 4: // config.bitbucket
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(BitbucketAccessConfig)
		err := b.DecodeMessage(msg)
		m.Config = &Integration_Bitbucket{msg}
		return true, err
	case 5: // config.github
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(GithubAccessConfig)
		err := b.DecodeMessage(msg)
		m.Config = &Integration_Github{msg}
		return true, err
	case 6: // config.aws
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(AWSAccessConfig)
		err := b.DecodeMessage(msg)
		m.Config = &Integration_Aws{msg}
		return true, err
	case 7: // config.nexus
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(NexusAccessConfig)
		err := b.DecodeMessage(msg)
		m.Config = &Integration_Nexus{msg}
		return true, err
	case 8: // config.slack
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(SlackAccessConfig)
		err := b.DecodeMessage(msg)
		m.Config = &Integration_Slack{msg}
		return true, err
	default:
		return false, nil
	}
}

func _Integration_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Integration)
	// config
	switch x := m.Config.(type) {
	case *Integration_Bitbucket:
		s := proto.Size(x.Bitbucket)
		n += proto.SizeVarint(4<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Integration_Github:
		s := proto.Size(x.Github)
		n += proto.SizeVarint(5<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Integration_Aws:
		s := proto.Size(x.Aws)
		n += proto.SizeVarint(6<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Integration_Nexus:
		s := proto.Size(x.Nexus)
		n += proto.SizeVarint(7<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Integration_Slack:
		s := proto.Size(x.Slack)
		n += proto.SizeVarint(8<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type IntegrationsList struct {
	Results []*Integration `protobuf:"bytes,1,rep,name=results" json:"results,omitempty"`
}

func (m *IntegrationsList) Reset()                    { *m = IntegrationsList{} }
func (m *IntegrationsList) String() string            { return proto.CompactTextString(m) }
func (*IntegrationsList) ProtoMessage()               {}
func (*IntegrationsList) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{1} }

func (m *IntegrationsList) GetResults() []*Integration {
	if m != nil {
		return m.Results
	}
	return nil
}

type BitbucketAccessConfig struct {
	Stuff string `protobuf:"bytes,1,opt,name=stuff" json:"stuff,omitempty"`
}

func (m *BitbucketAccessConfig) Reset()                    { *m = BitbucketAccessConfig{} }
func (m *BitbucketAccessConfig) String() string            { return proto.CompactTextString(m) }
func (*BitbucketAccessConfig) ProtoMessage()               {}
func (*BitbucketAccessConfig) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{2} }

func (m *BitbucketAccessConfig) GetStuff() string {
	if m != nil {
		return m.Stuff
	}
	return ""
}

type GithubAccessConfig struct {
	Stuff string `protobuf:"bytes,1,opt,name=stuff" json:"stuff,omitempty"`
}

func (m *GithubAccessConfig) Reset()                    { *m = GithubAccessConfig{} }
func (m *GithubAccessConfig) String() string            { return proto.CompactTextString(m) }
func (*GithubAccessConfig) ProtoMessage()               {}
func (*GithubAccessConfig) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{3} }

func (m *GithubAccessConfig) GetStuff() string {
	if m != nil {
		return m.Stuff
	}
	return ""
}

type AWSAccessConfig struct {
	AwsSecretKey   string `protobuf:"bytes,1,opt,name=aws_secret_key,json=awsSecretKey" json:"aws_secret_key,omitempty"`
	AwsSecretKeyId string `protobuf:"bytes,2,opt,name=aws_secret_key_id,json=awsSecretKeyId" json:"aws_secret_key_id,omitempty"`
}

func (m *AWSAccessConfig) Reset()                    { *m = AWSAccessConfig{} }
func (m *AWSAccessConfig) String() string            { return proto.CompactTextString(m) }
func (*AWSAccessConfig) ProtoMessage()               {}
func (*AWSAccessConfig) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{4} }

func (m *AWSAccessConfig) GetAwsSecretKey() string {
	if m != nil {
		return m.AwsSecretKey
	}
	return ""
}

func (m *AWSAccessConfig) GetAwsSecretKeyId() string {
	if m != nil {
		return m.AwsSecretKeyId
	}
	return ""
}

type BuildEnvironmentConfig struct {
	Language  Language  `protobuf:"varint,1,opt,name=language,enum=server.Language" json:"language,omitempty"`
	BuildTool BuildTool `protobuf:"varint,2,opt,name=build_tool,json=buildTool,enum=server.BuildTool" json:"build_tool,omitempty"`
}

func (m *BuildEnvironmentConfig) Reset()                    { *m = BuildEnvironmentConfig{} }
func (m *BuildEnvironmentConfig) String() string            { return proto.CompactTextString(m) }
func (*BuildEnvironmentConfig) ProtoMessage()               {}
func (*BuildEnvironmentConfig) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{5} }

func (m *BuildEnvironmentConfig) GetLanguage() Language {
	if m != nil {
		return m.Language
	}
	return Language_java
}

func (m *BuildEnvironmentConfig) GetBuildTool() BuildTool {
	if m != nil {
		return m.BuildTool
	}
	return BuildTool_mvn
}

type NexusAccessConfig struct {
	NexusUsername string                  `protobuf:"bytes,1,opt,name=nexus_username,json=nexusUsername" json:"nexus_username,omitempty"`
	NexusPassword string                  `protobuf:"bytes,2,opt,name=nexus_password,json=nexusPassword" json:"nexus_password,omitempty"`
	NexusHost     string                  `protobuf:"bytes,3,opt,name=nexus_host,json=nexusHost" json:"nexus_host,omitempty"`
	NexusPort     string                  `protobuf:"bytes,4,opt,name=nexus_port,json=nexusPort" json:"nexus_port,omitempty"`
	Environment   *BuildEnvironmentConfig `protobuf:"bytes,5,opt,name=environment" json:"environment,omitempty"`
}

func (m *NexusAccessConfig) Reset()                    { *m = NexusAccessConfig{} }
func (m *NexusAccessConfig) String() string            { return proto.CompactTextString(m) }
func (*NexusAccessConfig) ProtoMessage()               {}
func (*NexusAccessConfig) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{6} }

func (m *NexusAccessConfig) GetNexusUsername() string {
	if m != nil {
		return m.NexusUsername
	}
	return ""
}

func (m *NexusAccessConfig) GetNexusPassword() string {
	if m != nil {
		return m.NexusPassword
	}
	return ""
}

func (m *NexusAccessConfig) GetNexusHost() string {
	if m != nil {
		return m.NexusHost
	}
	return ""
}

func (m *NexusAccessConfig) GetNexusPort() string {
	if m != nil {
		return m.NexusPort
	}
	return ""
}

func (m *NexusAccessConfig) GetEnvironment() *BuildEnvironmentConfig {
	if m != nil {
		return m.Environment
	}
	return nil
}

type SlackAccessConfig struct {
	Stuff string `protobuf:"bytes,1,opt,name=stuff" json:"stuff,omitempty"`
}

func (m *SlackAccessConfig) Reset()                    { *m = SlackAccessConfig{} }
func (m *SlackAccessConfig) String() string            { return proto.CompactTextString(m) }
func (*SlackAccessConfig) ProtoMessage()               {}
func (*SlackAccessConfig) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{7} }

func (m *SlackAccessConfig) GetStuff() string {
	if m != nil {
		return m.Stuff
	}
	return ""
}

func init() {
	proto.RegisterType((*Integration)(nil), "server.Integration")
	proto.RegisterType((*IntegrationsList)(nil), "server.IntegrationsList")
	proto.RegisterType((*BitbucketAccessConfig)(nil), "server.BitbucketAccessConfig")
	proto.RegisterType((*GithubAccessConfig)(nil), "server.GithubAccessConfig")
	proto.RegisterType((*AWSAccessConfig)(nil), "server.AWSAccessConfig")
	proto.RegisterType((*BuildEnvironmentConfig)(nil), "server.BuildEnvironmentConfig")
	proto.RegisterType((*NexusAccessConfig)(nil), "server.NexusAccessConfig")
	proto.RegisterType((*SlackAccessConfig)(nil), "server.SlackAccessConfig")
	proto.RegisterEnum("server.Language", Language_name, Language_value)
	proto.RegisterEnum("server.BuildTool", BuildTool_name, BuildTool_value)
}

func init() { proto.RegisterFile("integration.proto", fileDescriptor2) }

var fileDescriptor2 = []byte{
	// 527 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x94, 0xdf, 0x8e, 0xd2, 0x40,
	0x14, 0xc6, 0xb7, 0xfc, 0x29, 0x70, 0x50, 0x2c, 0xe3, 0xbf, 0x6a, 0xb2, 0x86, 0x34, 0x9a, 0xb0,
	0xb8, 0x4b, 0x14, 0xbd, 0x35, 0x11, 0x8c, 0x71, 0x37, 0x6e, 0xcc, 0xa6, 0x68, 0xbc, 0x24, 0xd3,
	0x32, 0x94, 0x4a, 0x99, 0x21, 0x33, 0x53, 0x58, 0x9e, 0xcb, 0x27, 0xf2, 0x4d, 0x4c, 0xa7, 0x1d,
	0x28, 0x65, 0xf7, 0xee, 0xf0, 0x9d, 0xdf, 0x37, 0x93, 0xf9, 0xce, 0xa1, 0xd0, 0x0e, 0xa9, 0x24,
	0x01, 0xc7, 0x32, 0x64, 0xb4, 0xbf, 0xe2, 0x4c, 0x32, 0x64, 0x0a, 0xc2, 0xd7, 0x84, 0x3b, 0x7f,
	0x4b, 0xd0, 0xbc, 0xda, 0x77, 0x11, 0x82, 0x0a, 0xc5, 0x4b, 0x62, 0x1b, 0x1d, 0xa3, 0xdb, 0x70,
	0x55, 0x8d, 0x3e, 0x41, 0xc3, 0x0b, 0xa5, 0x17, 0xfb, 0x0b, 0x22, 0xed, 0x4a, 0xc7, 0xe8, 0x36,
	0x07, 0xa7, 0xfd, 0xd4, 0xdf, 0x1f, 0xe9, 0xc6, 0xd0, 0xf7, 0x89, 0x10, 0x5f, 0x18, 0x9d, 0x85,
	0xc1, 0xe5, 0x89, 0xbb, 0x77, 0xa0, 0x8f, 0x60, 0x06, 0xa1, 0x9c, 0xc7, 0x9e, 0x5d, 0x55, 0xde,
	0x97, 0xda, 0xfb, 0x4d, 0xa9, 0x05, 0x63, 0xc6, 0xa2, 0xb7, 0x50, 0xc6, 0x1b, 0x61, 0x9b, 0xca,
	0xf2, 0x5c, 0x5b, 0x86, 0xbf, 0xc7, 0x05, 0x3e, 0xa1, 0xd0, 0x7b, 0xa8, 0x52, 0x72, 0x1b, 0x0b,
	0xbb, 0xa6, 0xf0, 0x17, 0x1a, 0xff, 0x91, 0x88, 0x05, 0x43, 0x4a, 0x26, 0x16, 0x11, 0x61, 0x7f,
	0x61, 0xd7, 0x0f, 0x2d, 0xe3, 0x44, 0x2c, 0x5a, 0x14, 0x39, 0xaa, 0x83, 0xe9, 0x2b, 0xc9, 0x19,
	0x82, 0x95, 0x0b, 0x4d, 0x5c, 0x87, 0x42, 0xa2, 0x0b, 0xa8, 0x71, 0x22, 0xe2, 0x48, 0x0a, 0xdb,
	0xe8, 0x94, 0xbb, 0xcd, 0xc1, 0x63, 0x7d, 0x64, 0x0e, 0x75, 0x35, 0xe3, 0x5c, 0xc0, 0xd3, 0x3b,
	0xb3, 0x43, 0x4f, 0xa0, 0x2a, 0x64, 0x3c, 0x9b, 0x65, 0x23, 0x48, 0x7f, 0x38, 0x3d, 0x40, 0xc7,
	0x71, 0xdd, 0xc3, 0x7a, 0xf0, 0xa8, 0x90, 0x13, 0x7a, 0x0d, 0x2d, 0xbc, 0x11, 0x13, 0x41, 0x7c,
	0x4e, 0xe4, 0x64, 0x41, 0xb6, 0x99, 0xe3, 0x01, 0xde, 0x88, 0xb1, 0x12, 0xbf, 0x93, 0x2d, 0x3a,
	0x83, 0xf6, 0x21, 0x35, 0x09, 0xa7, 0x76, 0x49, 0x81, 0xad, 0x3c, 0x78, 0x35, 0x75, 0x6e, 0xe1,
	0xd9, 0x28, 0x0e, 0xa3, 0xe9, 0x57, 0xba, 0x0e, 0x39, 0xa3, 0x4b, 0x42, 0x65, 0x76, 0xd5, 0x39,
	0xd4, 0x23, 0x4c, 0x83, 0x18, 0x07, 0xe9, 0x16, 0xb5, 0x06, 0x96, 0x0e, 0xe2, 0x3a, 0xd3, 0xdd,
	0x1d, 0x81, 0xde, 0x01, 0x78, 0xc9, 0x39, 0x13, 0xc9, 0x58, 0xa4, 0xee, 0x6a, 0x0d, 0xda, 0xbb,
	0xe5, 0x4a, 0x3a, 0x3f, 0x19, 0x8b, 0xdc, 0x86, 0xa7, 0x4b, 0xe7, 0x9f, 0x01, 0xed, 0xa3, 0xb9,
	0xa2, 0x37, 0xd0, 0x52, 0x73, 0x9d, 0xc4, 0x82, 0xf0, 0xdc, 0x06, 0x3f, 0x54, 0xea, 0xaf, 0x4c,
	0xdc, 0x63, 0x2b, 0x2c, 0xc4, 0x86, 0x71, 0xfd, 0xbc, 0x14, 0xbb, 0xc9, 0x44, 0x74, 0x0a, 0x90,
	0x62, 0x73, 0x26, 0xa4, 0x5d, 0x56, 0x48, 0x43, 0x29, 0x97, 0x4c, 0xc8, 0x7d, 0x7b, 0xc5, 0x78,
	0xfa, 0x8f, 0xd0, 0xed, 0x1b, 0xc6, 0x25, 0xfa, 0x0c, 0x4d, 0xb2, 0x8f, 0x25, 0xdb, 0xfa, 0x57,
	0x07, 0x8f, 0x3a, 0x8a, 0xcd, 0xcd, 0x5b, 0x9c, 0x33, 0x68, 0x1f, 0xed, 0xe1, 0xdd, 0xc3, 0xee,
	0x9d, 0x43, 0x5d, 0xc7, 0x8a, 0xea, 0x50, 0xf9, 0x83, 0xd7, 0xd8, 0x3a, 0x41, 0x00, 0x66, 0xc0,
	0x92, 0x90, 0x2d, 0x23, 0xa9, 0x57, 0x5b, 0x39, 0x67, 0xd4, 0x2a, 0xf5, 0x3a, 0xd0, 0xd8, 0x85,
	0x8a, 0x6a, 0x50, 0x5e, 0xae, 0x69, 0x46, 0x73, 0x3c, 0x8d, 0x88, 0x65, 0x78, 0xa6, 0xfa, 0x3e,
	0x7c, 0xf8, 0x1f, 0x00, 0x00, 0xff, 0xff, 0xde, 0x26, 0x27, 0xbe, 0x34, 0x04, 0x00, 0x00,
}
