// Code generated by protoc-gen-go. DO NOT EDIT.
// source: integration.proto

package pipelines

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type Integration struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	// Types that are valid to be assigned to Config:
	//	*Integration_Bitbucket
	//	*Integration_Aws
	//	*Integration_Nexus
	//	*Integration_Slack
	Config isIntegration_Config `protobuf_oneof:"config"`
}

func (m *Integration) Reset()                    { *m = Integration{} }
func (m *Integration) String() string            { return proto.CompactTextString(m) }
func (*Integration) ProtoMessage()               {}
func (*Integration) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

type isIntegration_Config interface {
	isIntegration_Config()
}

type Integration_Bitbucket struct {
	Bitbucket *BitbucketAccessConfig `protobuf:"bytes,2,opt,name=bitbucket,oneof"`
}
type Integration_Aws struct {
	Aws *AWSConfig `protobuf:"bytes,3,opt,name=aws,oneof"`
}
type Integration_Nexus struct {
	Nexus *NexusConfig `protobuf:"bytes,4,opt,name=nexus,oneof"`
}
type Integration_Slack struct {
	Slack *SlackConfig `protobuf:"bytes,5,opt,name=slack,oneof"`
}

func (*Integration_Bitbucket) isIntegration_Config() {}
func (*Integration_Aws) isIntegration_Config()       {}
func (*Integration_Nexus) isIntegration_Config()     {}
func (*Integration_Slack) isIntegration_Config()     {}

func (m *Integration) GetConfig() isIntegration_Config {
	if m != nil {
		return m.Config
	}
	return nil
}

func (m *Integration) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Integration) GetBitbucket() *BitbucketAccessConfig {
	if x, ok := m.GetConfig().(*Integration_Bitbucket); ok {
		return x.Bitbucket
	}
	return nil
}

func (m *Integration) GetAws() *AWSConfig {
	if x, ok := m.GetConfig().(*Integration_Aws); ok {
		return x.Aws
	}
	return nil
}

func (m *Integration) GetNexus() *NexusConfig {
	if x, ok := m.GetConfig().(*Integration_Nexus); ok {
		return x.Nexus
	}
	return nil
}

func (m *Integration) GetSlack() *SlackConfig {
	if x, ok := m.GetConfig().(*Integration_Slack); ok {
		return x.Slack
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Integration) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Integration_OneofMarshaler, _Integration_OneofUnmarshaler, _Integration_OneofSizer, []interface{}{
		(*Integration_Bitbucket)(nil),
		(*Integration_Aws)(nil),
		(*Integration_Nexus)(nil),
		(*Integration_Slack)(nil),
	}
}

func _Integration_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Integration)
	// config
	switch x := m.Config.(type) {
	case *Integration_Bitbucket:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Bitbucket); err != nil {
			return err
		}
	case *Integration_Aws:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Aws); err != nil {
			return err
		}
	case *Integration_Nexus:
		b.EncodeVarint(4<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Nexus); err != nil {
			return err
		}
	case *Integration_Slack:
		b.EncodeVarint(5<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Slack); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("Integration.Config has unexpected type %T", x)
	}
	return nil
}

func _Integration_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Integration)
	switch tag {
	case 2: // config.bitbucket
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(BitbucketAccessConfig)
		err := b.DecodeMessage(msg)
		m.Config = &Integration_Bitbucket{msg}
		return true, err
	case 3: // config.aws
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(AWSConfig)
		err := b.DecodeMessage(msg)
		m.Config = &Integration_Aws{msg}
		return true, err
	case 4: // config.nexus
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(NexusConfig)
		err := b.DecodeMessage(msg)
		m.Config = &Integration_Nexus{msg}
		return true, err
	case 5: // config.slack
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(SlackConfig)
		err := b.DecodeMessage(msg)
		m.Config = &Integration_Slack{msg}
		return true, err
	default:
		return false, nil
	}
}

func _Integration_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Integration)
	// config
	switch x := m.Config.(type) {
	case *Integration_Bitbucket:
		s := proto.Size(x.Bitbucket)
		n += proto.SizeVarint(2<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Integration_Aws:
		s := proto.Size(x.Aws)
		n += proto.SizeVarint(3<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Integration_Nexus:
		s := proto.Size(x.Nexus)
		n += proto.SizeVarint(4<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Integration_Slack:
		s := proto.Size(x.Slack)
		n += proto.SizeVarint(5<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type IntegrationsList struct {
	Results []*Integration `protobuf:"bytes,1,rep,name=results" json:"results,omitempty"`
}

func (m *IntegrationsList) Reset()                    { *m = IntegrationsList{} }
func (m *IntegrationsList) String() string            { return proto.CompactTextString(m) }
func (*IntegrationsList) ProtoMessage()               {}
func (*IntegrationsList) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

func (m *IntegrationsList) GetResults() []*Integration {
	if m != nil {
		return m.Results
	}
	return nil
}

type BitbucketAccessConfig struct {
	Stuff string `protobuf:"bytes,1,opt,name=stuff" json:"stuff,omitempty"`
}

func (m *BitbucketAccessConfig) Reset()                    { *m = BitbucketAccessConfig{} }
func (m *BitbucketAccessConfig) String() string            { return proto.CompactTextString(m) }
func (*BitbucketAccessConfig) ProtoMessage()               {}
func (*BitbucketAccessConfig) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{2} }

func (m *BitbucketAccessConfig) GetStuff() string {
	if m != nil {
		return m.Stuff
	}
	return ""
}

type GithubAccessConfig struct {
	Stuff string `protobuf:"bytes,1,opt,name=stuff" json:"stuff,omitempty"`
}

func (m *GithubAccessConfig) Reset()                    { *m = GithubAccessConfig{} }
func (m *GithubAccessConfig) String() string            { return proto.CompactTextString(m) }
func (*GithubAccessConfig) ProtoMessage()               {}
func (*GithubAccessConfig) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{3} }

func (m *GithubAccessConfig) GetStuff() string {
	if m != nil {
		return m.Stuff
	}
	return ""
}

type AWSConfig struct {
	AwsSecretKey   string `protobuf:"bytes,1,opt,name=aws_secret_key,json=awsSecretKey" json:"aws_secret_key,omitempty"`
	AwsSecretKeyId string `protobuf:"bytes,2,opt,name=aws_secret_key_id,json=awsSecretKeyId" json:"aws_secret_key_id,omitempty"`
}

func (m *AWSConfig) Reset()                    { *m = AWSConfig{} }
func (m *AWSConfig) String() string            { return proto.CompactTextString(m) }
func (*AWSConfig) ProtoMessage()               {}
func (*AWSConfig) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{4} }

func (m *AWSConfig) GetAwsSecretKey() string {
	if m != nil {
		return m.AwsSecretKey
	}
	return ""
}

func (m *AWSConfig) GetAwsSecretKeyId() string {
	if m != nil {
		return m.AwsSecretKeyId
	}
	return ""
}

type NexusConfig struct {
	Stuff string `protobuf:"bytes,1,opt,name=stuff" json:"stuff,omitempty"`
}

func (m *NexusConfig) Reset()                    { *m = NexusConfig{} }
func (m *NexusConfig) String() string            { return proto.CompactTextString(m) }
func (*NexusConfig) ProtoMessage()               {}
func (*NexusConfig) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{5} }

func (m *NexusConfig) GetStuff() string {
	if m != nil {
		return m.Stuff
	}
	return ""
}

type SlackConfig struct {
	Stuff string `protobuf:"bytes,1,opt,name=stuff" json:"stuff,omitempty"`
}

func (m *SlackConfig) Reset()                    { *m = SlackConfig{} }
func (m *SlackConfig) String() string            { return proto.CompactTextString(m) }
func (*SlackConfig) ProtoMessage()               {}
func (*SlackConfig) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{6} }

func (m *SlackConfig) GetStuff() string {
	if m != nil {
		return m.Stuff
	}
	return ""
}

func init() {
	proto.RegisterType((*Integration)(nil), "pipelines.Integration")
	proto.RegisterType((*IntegrationsList)(nil), "pipelines.IntegrationsList")
	proto.RegisterType((*BitbucketAccessConfig)(nil), "pipelines.BitbucketAccessConfig")
	proto.RegisterType((*GithubAccessConfig)(nil), "pipelines.GithubAccessConfig")
	proto.RegisterType((*AWSConfig)(nil), "pipelines.AWSConfig")
	proto.RegisterType((*NexusConfig)(nil), "pipelines.NexusConfig")
	proto.RegisterType((*SlackConfig)(nil), "pipelines.SlackConfig")
}

func init() { proto.RegisterFile("integration.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 321 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0xd2, 0x4f, 0x4f, 0xf2, 0x40,
	0x10, 0x06, 0xf0, 0xb7, 0x2f, 0x7f, 0xb4, 0x53, 0x43, 0x64, 0x83, 0xa6, 0xc7, 0xa6, 0x78, 0x40,
	0x13, 0x1b, 0xa3, 0x5f, 0x40, 0xd0, 0x44, 0x89, 0xc6, 0x43, 0x39, 0x78, 0x31, 0x21, 0xdb, 0x65,
	0xc0, 0x0d, 0xb8, 0x25, 0x9d, 0x6d, 0x90, 0x4f, 0xee, 0xd5, 0x74, 0x81, 0xb2, 0x2a, 0x26, 0xde,
	0xda, 0xa7, 0xbf, 0xd9, 0x74, 0x9e, 0x16, 0x9a, 0x52, 0x69, 0x9c, 0x64, 0x5c, 0xcb, 0x54, 0x45,
	0xf3, 0x2c, 0xd5, 0x29, 0x73, 0xe7, 0x72, 0x8e, 0x33, 0xa9, 0x90, 0xc2, 0x0f, 0x07, 0xbc, 0xfe,
	0x16, 0x30, 0x06, 0x55, 0xc5, 0xdf, 0xd0, 0x77, 0x02, 0xa7, 0xe3, 0xc6, 0xe6, 0x9a, 0x5d, 0x83,
	0x9b, 0x48, 0x9d, 0xe4, 0x62, 0x8a, 0xda, 0xff, 0x1f, 0x38, 0x1d, 0xef, 0x32, 0x88, 0xca, 0x23,
	0xa2, 0xde, 0xe6, 0x59, 0x57, 0x08, 0x24, 0xba, 0x49, 0xd5, 0x58, 0x4e, 0xee, 0xff, 0xc5, 0xdb,
	0x21, 0xd6, 0x81, 0x0a, 0x5f, 0x90, 0x5f, 0x31, 0xb3, 0x2d, 0x6b, 0xb6, 0xfb, 0x3c, 0x28, 0x7d,
	0x41, 0x58, 0x04, 0x35, 0x85, 0xef, 0x39, 0xf9, 0x55, 0x63, 0x8f, 0x2d, 0xfb, 0x54, 0xe4, 0xa5,
	0x5e, 0xb1, 0xc2, 0xd3, 0x8c, 0x8b, 0xa9, 0x5f, 0xfb, 0xe1, 0x07, 0x45, 0xbe, 0xf5, 0x86, 0xf5,
	0xf6, 0xa1, 0x2e, 0x4c, 0x14, 0xde, 0xc2, 0xa1, 0xb5, 0x38, 0x3d, 0x4a, 0xd2, 0xec, 0x02, 0xf6,
	0x32, 0xa4, 0x7c, 0xa6, 0xc9, 0x77, 0x82, 0xca, 0xb7, 0xf3, 0x2c, 0x1d, 0x6f, 0x58, 0x78, 0x0e,
	0x47, 0x3b, 0xf7, 0x67, 0x2d, 0xa8, 0x91, 0xce, 0xc7, 0xe3, 0x75, 0x93, 0xab, 0x9b, 0xf0, 0x0c,
	0xd8, 0x9d, 0xd4, 0xaf, 0x79, 0xf2, 0x07, 0xfb, 0x02, 0x6e, 0x59, 0x0f, 0x3b, 0x81, 0x06, 0x5f,
	0xd0, 0x90, 0x50, 0x64, 0xa8, 0x87, 0x53, 0x5c, 0xae, 0xed, 0x01, 0x5f, 0xd0, 0xc0, 0x84, 0x0f,
	0xb8, 0x64, 0xa7, 0xd0, 0xfc, 0xaa, 0x86, 0x72, 0x64, 0xbe, 0x98, 0x1b, 0x37, 0x6c, 0xd8, 0x1f,
	0x85, 0x6d, 0xf0, 0xac, 0x42, 0x7f, 0x79, 0x85, 0x36, 0x78, 0x56, 0x8b, 0xbb, 0x51, 0x52, 0x37,
	0x3f, 0xd5, 0xd5, 0x67, 0x00, 0x00, 0x00, 0xff, 0xff, 0x73, 0xb7, 0x1d, 0x41, 0x69, 0x02, 0x00,
	0x00,
}
