// Code generated by protoc-gen-go. DO NOT EDIT.
// source: cmd.proto

/*
Package cmd is a generated protocol buffer package.

It is generated from these files:
	cmd.proto

It has these top-level messages:
	ResourceCmdConfig
	CmdConfig
	CmdOperation
	Option
*/
package cmd

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Operation int32

const (
	Operation_create Operation = 1
	Operation_get    Operation = 2
	Operation_list   Operation = 3
	Operation_update Operation = 4
	Operation_patch  Operation = 5
	Operation_delete Operation = 6
	Operation_apply  Operation = 7
)

var Operation_name = map[int32]string{
	1: "create",
	2: "get",
	3: "list",
	4: "update",
	5: "patch",
	6: "delete",
	7: "apply",
}
var Operation_value = map[string]int32{
	"create": 1,
	"get":    2,
	"list":   3,
	"update": 4,
	"patch":  5,
	"delete": 6,
	"apply":  7,
}

func (x Operation) Enum() *Operation {
	p := new(Operation)
	*p = x
	return p
}
func (x Operation) String() string {
	return proto.EnumName(Operation_name, int32(x))
}
func (x *Operation) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Operation_value, data, "Operation")
	if err != nil {
		return err
	}
	*x = Operation(value)
	return nil
}
func (Operation) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type ResourceCmdConfig struct {
	Resources        []*CmdConfig `protobuf:"bytes,1,rep,name=Resources" json:"Resources,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *ResourceCmdConfig) Reset()                    { *m = ResourceCmdConfig{} }
func (m *ResourceCmdConfig) String() string            { return proto.CompactTextString(m) }
func (*ResourceCmdConfig) ProtoMessage()               {}
func (*ResourceCmdConfig) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ResourceCmdConfig) GetResources() []*CmdConfig {
	if m != nil {
		return m.Resources
	}
	return nil
}

type CmdConfig struct {
	Name             *string         `protobuf:"bytes,1,req,name=Name" json:"Name,omitempty"`
	Usage            *string         `protobuf:"bytes,2,req,name=Usage" json:"Usage,omitempty"`
	ShortDescription *string         `protobuf:"bytes,3,req,name=ShortDescription" json:"ShortDescription,omitempty"`
	LongDescription  *string         `protobuf:"bytes,4,req,name=LongDescription" json:"LongDescription,omitempty"`
	Operations       []*CmdOperation `protobuf:"bytes,5,rep,name=Operations" json:"Operations,omitempty"`
	XXX_unrecognized []byte          `json:"-"`
}

func (m *CmdConfig) Reset()                    { *m = CmdConfig{} }
func (m *CmdConfig) String() string            { return proto.CompactTextString(m) }
func (*CmdConfig) ProtoMessage()               {}
func (*CmdConfig) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *CmdConfig) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *CmdConfig) GetUsage() string {
	if m != nil && m.Usage != nil {
		return *m.Usage
	}
	return ""
}

func (m *CmdConfig) GetShortDescription() string {
	if m != nil && m.ShortDescription != nil {
		return *m.ShortDescription
	}
	return ""
}

func (m *CmdConfig) GetLongDescription() string {
	if m != nil && m.LongDescription != nil {
		return *m.LongDescription
	}
	return ""
}

func (m *CmdConfig) GetOperations() []*CmdOperation {
	if m != nil {
		return m.Operations
	}
	return nil
}

type CmdOperation struct {
	Name             *Operation `protobuf:"varint,1,req,name=Name,enum=cmd.Operation" json:"Name,omitempty"`
	Options          []*Option  `protobuf:"bytes,2,rep,name=Options" json:"Options,omitempty"`
	XXX_unrecognized []byte     `json:"-"`
}

func (m *CmdOperation) Reset()                    { *m = CmdOperation{} }
func (m *CmdOperation) String() string            { return proto.CompactTextString(m) }
func (*CmdOperation) ProtoMessage()               {}
func (*CmdOperation) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *CmdOperation) GetName() Operation {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return Operation_create
}

func (m *CmdOperation) GetOptions() []*Option {
	if m != nil {
		return m.Options
	}
	return nil
}

type Option struct {
	Name             *string `protobuf:"bytes,1,req,name=Name" json:"Name,omitempty"`
	ShortName        *string `protobuf:"bytes,2,req,name=ShortName" json:"ShortName,omitempty"`
	Default          *string `protobuf:"bytes,3,req,name=Default" json:"Default,omitempty"`
	Type             *string `protobuf:"bytes,4,req,name=Type" json:"Type,omitempty"`
	Description      *string `protobuf:"bytes,5,req,name=Description" json:"Description,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Option) Reset()                    { *m = Option{} }
func (m *Option) String() string            { return proto.CompactTextString(m) }
func (*Option) ProtoMessage()               {}
func (*Option) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Option) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *Option) GetShortName() string {
	if m != nil && m.ShortName != nil {
		return *m.ShortName
	}
	return ""
}

func (m *Option) GetDefault() string {
	if m != nil && m.Default != nil {
		return *m.Default
	}
	return ""
}

func (m *Option) GetType() string {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return ""
}

func (m *Option) GetDescription() string {
	if m != nil && m.Description != nil {
		return *m.Description
	}
	return ""
}

func init() {
	proto.RegisterType((*ResourceCmdConfig)(nil), "cmd.ResourceCmdConfig")
	proto.RegisterType((*CmdConfig)(nil), "cmd.CmdConfig")
	proto.RegisterType((*CmdOperation)(nil), "cmd.CmdOperation")
	proto.RegisterType((*Option)(nil), "cmd.Option")
	proto.RegisterEnum("cmd.Operation", Operation_name, Operation_value)
}

func init() { proto.RegisterFile("cmd.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 329 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0xcf, 0x4a, 0xf3, 0x40,
	0x14, 0xc5, 0xc9, 0xbf, 0xe6, 0x9b, 0xdb, 0x8f, 0x3a, 0xbd, 0xb8, 0xc8, 0xc2, 0x45, 0x09, 0x08,
	0xa5, 0x48, 0x41, 0xdf, 0x40, 0xda, 0xa5, 0x58, 0x88, 0x0a, 0xba, 0x1c, 0x92, 0xdb, 0x34, 0x90,
	0x74, 0x86, 0x64, 0xba, 0xe8, 0x2b, 0xf8, 0x50, 0x3e, 0x9b, 0xcc, 0x24, 0x69, 0x82, 0xba, 0xbb,
	0xf7, 0x9c, 0xdf, 0x4d, 0xe6, 0x1c, 0x60, 0x69, 0x95, 0xad, 0x55, 0x2d, 0xb5, 0x44, 0x2f, 0xad,
	0xb2, 0xf8, 0x11, 0xe6, 0x09, 0x35, 0xf2, 0x54, 0xa7, 0xb4, 0xa9, 0xb2, 0x8d, 0x3c, 0xee, 0x8b,
	0x1c, 0xef, 0x80, 0xf5, 0x62, 0x13, 0x39, 0x0b, 0x6f, 0x39, 0x7d, 0x98, 0xad, 0xcd, 0xe1, 0x05,
	0x49, 0x06, 0x20, 0xfe, 0x72, 0x80, 0x0d, 0xb7, 0x08, 0xfe, 0xb3, 0xa8, 0x28, 0x72, 0x16, 0xee,
	0x92, 0x25, 0x76, 0xc6, 0x6b, 0x08, 0xde, 0x1a, 0x91, 0x53, 0xe4, 0x5a, 0xb1, 0x5d, 0x70, 0x05,
	0xfc, 0xe5, 0x20, 0x6b, 0xbd, 0xa5, 0x26, 0xad, 0x0b, 0xa5, 0x0b, 0x79, 0x8c, 0x3c, 0x0b, 0xfc,
	0xd2, 0x71, 0x09, 0x57, 0x4f, 0xf2, 0x98, 0x8f, 0x51, 0xdf, 0xa2, 0x3f, 0x65, 0xbc, 0x07, 0xd8,
	0x29, 0xaa, 0x85, 0x59, 0x9a, 0x28, 0xb0, 0x8f, 0x9f, 0xf7, 0x8f, 0xbf, 0x38, 0xc9, 0x08, 0x8a,
	0x3f, 0xe0, 0xff, 0xd8, 0xc3, 0x78, 0x14, 0x61, 0xd6, 0x25, 0x1f, 0x2e, 0xdb, 0x48, 0xb7, 0x10,
	0xee, 0x54, 0xfb, 0x0f, 0xd7, 0xfe, 0x63, 0xda, 0x61, 0x96, 0xe9, 0xbd, 0xf8, 0xd3, 0x81, 0x49,
	0x3b, 0xff, 0x59, 0xcc, 0x0d, 0x30, 0x1b, 0xd5, 0x1a, 0x6d, 0x39, 0x83, 0x80, 0x11, 0x84, 0x5b,
	0xda, 0x8b, 0x53, 0xa9, 0xbb, 0x5e, 0xfa, 0xd5, 0x7c, 0xeb, 0xf5, 0xac, 0xa8, 0xeb, 0xc0, 0xce,
	0xb8, 0x80, 0xe9, 0xb8, 0x9e, 0xc0, 0x5a, 0x63, 0x69, 0xf5, 0x0e, 0x6c, 0x08, 0x09, 0x30, 0x49,
	0x6b, 0x12, 0x9a, 0xb8, 0x83, 0x21, 0x78, 0x39, 0x69, 0xee, 0xe2, 0x3f, 0xf0, 0xcb, 0xa2, 0xd1,
	0xdc, 0x33, 0xf6, 0x49, 0x65, 0xc6, 0xf6, 0x91, 0x41, 0xa0, 0x84, 0x4e, 0x0f, 0x3c, 0x30, 0x72,
	0x46, 0x25, 0x69, 0xe2, 0x13, 0x23, 0x0b, 0xa5, 0xca, 0x33, 0x0f, 0xbf, 0x03, 0x00, 0x00, 0xff,
	0xff, 0x10, 0x69, 0x2e, 0x3c, 0x56, 0x02, 0x00, 0x00,
}
