// Code generated by protoc-gen-go. DO NOT EDIT.
// source: host.proto

package leveler

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/empty"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type HostId struct {
	Id string `protobuf:"bytes,1,opt,name=Id" json:"Id,omitempty"`
}

func (m *HostId) Reset()                    { *m = HostId{} }
func (m *HostId) String() string            { return proto.CompactTextString(m) }
func (*HostId) ProtoMessage()               {}
func (*HostId) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{0} }

func (m *HostId) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type Host struct {
	Id           string         `protobuf:"bytes,1,opt,name=Id" json:"Id,omitempty"`
	Name         string         `protobuf:"bytes,2,opt,name=Name" json:"Name,omitempty"`
	Description  string         `protobuf:"bytes,3,opt,name=Description" json:"Description,omitempty"`
	Constraints  []*Constraint  `protobuf:"bytes,4,rep,name=Constraints" json:"Constraints,omitempty"`
	Roles        []*Role        `protobuf:"bytes,5,rep,name=Roles" json:"Roles,omitempty"`
	Requirements []*Requirement `protobuf:"bytes,6,rep,name=Requirements" json:"Requirements,omitempty"`
}

func (m *Host) Reset()                    { *m = Host{} }
func (m *Host) String() string            { return proto.CompactTextString(m) }
func (*Host) ProtoMessage()               {}
func (*Host) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{1} }

func (m *Host) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Host) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Host) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Host) GetConstraints() []*Constraint {
	if m != nil {
		return m.Constraints
	}
	return nil
}

func (m *Host) GetRoles() []*Role {
	if m != nil {
		return m.Roles
	}
	return nil
}

func (m *Host) GetRequirements() []*Requirement {
	if m != nil {
		return m.Requirements
	}
	return nil
}

type HostList struct {
	Results []*Host `protobuf:"bytes,1,rep,name=Results" json:"Results,omitempty"`
}

func (m *HostList) Reset()                    { *m = HostList{} }
func (m *HostList) String() string            { return proto.CompactTextString(m) }
func (*HostList) ProtoMessage()               {}
func (*HostList) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{2} }

func (m *HostList) GetResults() []*Host {
	if m != nil {
		return m.Results
	}
	return nil
}

func init() {
	proto.RegisterType((*HostId)(nil), "leveler.HostId")
	proto.RegisterType((*Host)(nil), "leveler.Host")
	proto.RegisterType((*HostList)(nil), "leveler.HostList")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for HostEndpoint service

type HostEndpointClient interface {
	GetHost(ctx context.Context, in *HostId, opts ...grpc.CallOption) (*Host, error)
	ListHosts(ctx context.Context, in *Query, opts ...grpc.CallOption) (*HostList, error)
	CreateHost(ctx context.Context, in *Host, opts ...grpc.CallOption) (*HostId, error)
	UpdateHost(ctx context.Context, in *Host, opts ...grpc.CallOption) (*Host, error)
	DeleteHost(ctx context.Context, in *HostId, opts ...grpc.CallOption) (*google_protobuf.Empty, error)
}

type hostEndpointClient struct {
	cc *grpc.ClientConn
}

func NewHostEndpointClient(cc *grpc.ClientConn) HostEndpointClient {
	return &hostEndpointClient{cc}
}

func (c *hostEndpointClient) GetHost(ctx context.Context, in *HostId, opts ...grpc.CallOption) (*Host, error) {
	out := new(Host)
	err := grpc.Invoke(ctx, "/leveler.HostEndpoint/GetHost", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostEndpointClient) ListHosts(ctx context.Context, in *Query, opts ...grpc.CallOption) (*HostList, error) {
	out := new(HostList)
	err := grpc.Invoke(ctx, "/leveler.HostEndpoint/ListHosts", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostEndpointClient) CreateHost(ctx context.Context, in *Host, opts ...grpc.CallOption) (*HostId, error) {
	out := new(HostId)
	err := grpc.Invoke(ctx, "/leveler.HostEndpoint/CreateHost", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostEndpointClient) UpdateHost(ctx context.Context, in *Host, opts ...grpc.CallOption) (*Host, error) {
	out := new(Host)
	err := grpc.Invoke(ctx, "/leveler.HostEndpoint/UpdateHost", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostEndpointClient) DeleteHost(ctx context.Context, in *HostId, opts ...grpc.CallOption) (*google_protobuf.Empty, error) {
	out := new(google_protobuf.Empty)
	err := grpc.Invoke(ctx, "/leveler.HostEndpoint/DeleteHost", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for HostEndpoint service

type HostEndpointServer interface {
	GetHost(context.Context, *HostId) (*Host, error)
	ListHosts(context.Context, *Query) (*HostList, error)
	CreateHost(context.Context, *Host) (*HostId, error)
	UpdateHost(context.Context, *Host) (*Host, error)
	DeleteHost(context.Context, *HostId) (*google_protobuf.Empty, error)
}

func RegisterHostEndpointServer(s *grpc.Server, srv HostEndpointServer) {
	s.RegisterService(&_HostEndpoint_serviceDesc, srv)
}

func _HostEndpoint_GetHost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HostId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostEndpointServer).GetHost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/leveler.HostEndpoint/GetHost",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostEndpointServer).GetHost(ctx, req.(*HostId))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostEndpoint_ListHosts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Query)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostEndpointServer).ListHosts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/leveler.HostEndpoint/ListHosts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostEndpointServer).ListHosts(ctx, req.(*Query))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostEndpoint_CreateHost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Host)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostEndpointServer).CreateHost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/leveler.HostEndpoint/CreateHost",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostEndpointServer).CreateHost(ctx, req.(*Host))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostEndpoint_UpdateHost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Host)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostEndpointServer).UpdateHost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/leveler.HostEndpoint/UpdateHost",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostEndpointServer).UpdateHost(ctx, req.(*Host))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostEndpoint_DeleteHost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HostId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostEndpointServer).DeleteHost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/leveler.HostEndpoint/DeleteHost",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostEndpointServer).DeleteHost(ctx, req.(*HostId))
	}
	return interceptor(ctx, in, info, handler)
}

var _HostEndpoint_serviceDesc = grpc.ServiceDesc{
	ServiceName: "leveler.HostEndpoint",
	HandlerType: (*HostEndpointServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetHost",
			Handler:    _HostEndpoint_GetHost_Handler,
		},
		{
			MethodName: "ListHosts",
			Handler:    _HostEndpoint_ListHosts_Handler,
		},
		{
			MethodName: "CreateHost",
			Handler:    _HostEndpoint_CreateHost_Handler,
		},
		{
			MethodName: "UpdateHost",
			Handler:    _HostEndpoint_UpdateHost_Handler,
		},
		{
			MethodName: "DeleteHost",
			Handler:    _HostEndpoint_DeleteHost_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "host.proto",
}

func init() { proto.RegisterFile("host.proto", fileDescriptor3) }

var fileDescriptor3 = []byte{
	// 368 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x92, 0xdf, 0x6e, 0xda, 0x30,
	0x14, 0xc6, 0x93, 0xf0, 0x6f, 0x1c, 0x18, 0x1b, 0xde, 0x34, 0x59, 0xd9, 0x0d, 0xca, 0x2e, 0x86,
	0xb4, 0x29, 0x4c, 0xa0, 0x69, 0xbb, 0x07, 0xd4, 0x46, 0xaa, 0x2a, 0xd5, 0x52, 0x1f, 0x00, 0xc8,
	0x29, 0x8d, 0x64, 0xe2, 0xd4, 0x76, 0x2a, 0x71, 0xdf, 0x27, 0xed, 0x93, 0x54, 0x36, 0x21, 0x21,
	0xa0, 0xde, 0x1d, 0x7f, 0xbf, 0xef, 0xf8, 0x3b, 0xb6, 0x0e, 0xc0, 0xa3, 0x50, 0x3a, 0xcc, 0xa4,
	0xd0, 0x82, 0x74, 0x38, 0x3e, 0x23, 0x47, 0xe9, 0x0f, 0x25, 0x3e, 0xe5, 0x89, 0xc4, 0x1d, 0xa6,
	0x05, 0xf3, 0x3f, 0x6f, 0x44, 0xaa, 0xb4, 0x5c, 0x25, 0xa5, 0x02, 0x52, 0x70, 0x3c, 0xd6, 0xb9,
	0x4e, 0x78, 0x51, 0x7f, 0xdf, 0x0a, 0xb1, 0xe5, 0x38, 0xb1, 0xa7, 0x75, 0xfe, 0x30, 0xc1, 0x5d,
	0xa6, 0xf7, 0x07, 0x18, 0x50, 0x68, 0x5f, 0x0b, 0xa5, 0xa3, 0x98, 0x0c, 0xc0, 0x8b, 0x62, 0xea,
	0x8e, 0xdc, 0x71, 0x97, 0x79, 0x51, 0x1c, 0xbc, 0xba, 0xd0, 0x34, 0xe8, 0x1c, 0x10, 0x02, 0xcd,
	0xdb, 0xd5, 0x0e, 0xa9, 0x67, 0x15, 0x5b, 0x93, 0x11, 0xf4, 0x16, 0xa8, 0x36, 0x32, 0xc9, 0x74,
	0x22, 0x52, 0xda, 0xb0, 0xe8, 0x54, 0x22, 0x7f, 0xa1, 0x37, 0x2f, 0x27, 0x56, 0xb4, 0x39, 0x6a,
	0x8c, 0x7b, 0xd3, 0x2f, 0x61, 0xf1, 0xc2, 0xb0, 0x62, 0xec, 0xd4, 0x47, 0x7e, 0x40, 0x8b, 0x09,
	0x8e, 0x8a, 0xb6, 0x6c, 0xc3, 0xc7, 0xb2, 0xc1, 0xa8, 0xec, 0xc0, 0xc8, 0x7f, 0xe8, 0xb3, 0xea,
	0x83, 0x14, 0x6d, 0x5b, 0xef, 0xd7, 0xca, 0x5b, 0x41, 0x56, 0x73, 0x06, 0x33, 0xf8, 0x60, 0xde,
	0x78, 0x93, 0x28, 0x4d, 0x7e, 0x42, 0x87, 0xa1, 0xca, 0xb9, 0x56, 0xd4, 0x3d, 0x0b, 0x33, 0x1e,
	0x76, 0xa4, 0xd3, 0x17, 0x0f, 0xfa, 0x46, 0x59, 0xa6, 0x71, 0x26, 0x92, 0x54, 0x93, 0x5f, 0xd0,
	0xb9, 0x42, 0x6d, 0x3f, 0xeb, 0x53, 0xad, 0x27, 0x8a, 0xfd, 0xfa, 0x25, 0x81, 0x43, 0xfe, 0x40,
	0xd7, 0xc4, 0x99, 0x93, 0x22, 0x83, 0x92, 0xde, 0xe5, 0x28, 0xf7, 0xfe, 0xb0, 0xe6, 0x36, 0xbe,
	0xc0, 0x21, 0x21, 0xc0, 0x5c, 0xe2, 0x4a, 0xa3, 0x4d, 0xa8, 0x5f, 0xe8, 0x9f, 0x07, 0x06, 0x0e,
	0xf9, 0x0d, 0x70, 0x9f, 0xc5, 0xef, 0xf8, 0x2f, 0xe6, 0xf9, 0x07, 0xb0, 0x40, 0x8e, 0x85, 0xfb,
	0x62, 0xfe, 0x6f, 0xe1, 0x61, 0x7d, 0xc2, 0xe3, 0xfa, 0x84, 0x4b, 0xb3, 0x3e, 0x81, 0xb3, 0x6e,
	0x5b, 0x65, 0xf6, 0x16, 0x00, 0x00, 0xff, 0xff, 0x27, 0x8f, 0x6d, 0x7c, 0xb2, 0x02, 0x00, 0x00,
}
