// Code generated by protoc-gen-go. DO NOT EDIT.
// source: requirement.proto

package leveler

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/empty"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type RequirementId struct {
	Id string `protobuf:"bytes,1,opt,name=Id" json:"Id,omitempty"`
}

func (m *RequirementId) Reset()                    { *m = RequirementId{} }
func (m *RequirementId) String() string            { return proto.CompactTextString(m) }
func (*RequirementId) ProtoMessage()               {}
func (*RequirementId) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{0} }

func (m *RequirementId) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type Requirement struct {
	Id          string            `protobuf:"bytes,1,opt,name=Id" json:"Id,omitempty"`
	Name        string            `protobuf:"bytes,2,opt,name=Name" json:"Name,omitempty"`
	Description string            `protobuf:"bytes,3,opt,name=Description" json:"Description,omitempty"`
	Actions     []*Action         `protobuf:"bytes,4,rep,name=Actions" json:"Actions,omitempty"`
	Tests       []*Action         `protobuf:"bytes,5,rep,name=Tests" json:"Tests,omitempty"`
	Constraints []*Constraint     `protobuf:"bytes,6,rep,name=Constraints" json:"Constraints,omitempty"`
	Environment map[string]string `protobuf:"bytes,7,rep,name=Environment" json:"Environment,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *Requirement) Reset()                    { *m = Requirement{} }
func (m *Requirement) String() string            { return proto.CompactTextString(m) }
func (*Requirement) ProtoMessage()               {}
func (*Requirement) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{1} }

func (m *Requirement) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Requirement) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Requirement) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Requirement) GetActions() []*Action {
	if m != nil {
		return m.Actions
	}
	return nil
}

func (m *Requirement) GetTests() []*Action {
	if m != nil {
		return m.Tests
	}
	return nil
}

func (m *Requirement) GetConstraints() []*Constraint {
	if m != nil {
		return m.Constraints
	}
	return nil
}

func (m *Requirement) GetEnvironment() map[string]string {
	if m != nil {
		return m.Environment
	}
	return nil
}

type RequirementList struct {
	Results []*Requirement `protobuf:"bytes,1,rep,name=Results" json:"Results,omitempty"`
}

func (m *RequirementList) Reset()                    { *m = RequirementList{} }
func (m *RequirementList) String() string            { return proto.CompactTextString(m) }
func (*RequirementList) ProtoMessage()               {}
func (*RequirementList) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{2} }

func (m *RequirementList) GetResults() []*Requirement {
	if m != nil {
		return m.Results
	}
	return nil
}

func init() {
	proto.RegisterType((*RequirementId)(nil), "leveler.RequirementId")
	proto.RegisterType((*Requirement)(nil), "leveler.Requirement")
	proto.RegisterType((*RequirementList)(nil), "leveler.RequirementList")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for RequirementEndpoint service

type RequirementEndpointClient interface {
	GetRequirement(ctx context.Context, in *RequirementId, opts ...grpc.CallOption) (*Requirement, error)
	ListRequirements(ctx context.Context, in *Query, opts ...grpc.CallOption) (*RequirementList, error)
	CreateRequirement(ctx context.Context, in *Requirement, opts ...grpc.CallOption) (*RequirementId, error)
	UpdateRequirement(ctx context.Context, in *Requirement, opts ...grpc.CallOption) (*Requirement, error)
	DeleteRequirement(ctx context.Context, in *RequirementId, opts ...grpc.CallOption) (*google_protobuf.Empty, error)
}

type requirementEndpointClient struct {
	cc *grpc.ClientConn
}

func NewRequirementEndpointClient(cc *grpc.ClientConn) RequirementEndpointClient {
	return &requirementEndpointClient{cc}
}

func (c *requirementEndpointClient) GetRequirement(ctx context.Context, in *RequirementId, opts ...grpc.CallOption) (*Requirement, error) {
	out := new(Requirement)
	err := grpc.Invoke(ctx, "/leveler.RequirementEndpoint/GetRequirement", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *requirementEndpointClient) ListRequirements(ctx context.Context, in *Query, opts ...grpc.CallOption) (*RequirementList, error) {
	out := new(RequirementList)
	err := grpc.Invoke(ctx, "/leveler.RequirementEndpoint/ListRequirements", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *requirementEndpointClient) CreateRequirement(ctx context.Context, in *Requirement, opts ...grpc.CallOption) (*RequirementId, error) {
	out := new(RequirementId)
	err := grpc.Invoke(ctx, "/leveler.RequirementEndpoint/CreateRequirement", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *requirementEndpointClient) UpdateRequirement(ctx context.Context, in *Requirement, opts ...grpc.CallOption) (*Requirement, error) {
	out := new(Requirement)
	err := grpc.Invoke(ctx, "/leveler.RequirementEndpoint/UpdateRequirement", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *requirementEndpointClient) DeleteRequirement(ctx context.Context, in *RequirementId, opts ...grpc.CallOption) (*google_protobuf.Empty, error) {
	out := new(google_protobuf.Empty)
	err := grpc.Invoke(ctx, "/leveler.RequirementEndpoint/DeleteRequirement", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for RequirementEndpoint service

type RequirementEndpointServer interface {
	GetRequirement(context.Context, *RequirementId) (*Requirement, error)
	ListRequirements(context.Context, *Query) (*RequirementList, error)
	CreateRequirement(context.Context, *Requirement) (*RequirementId, error)
	UpdateRequirement(context.Context, *Requirement) (*Requirement, error)
	DeleteRequirement(context.Context, *RequirementId) (*google_protobuf.Empty, error)
}

func RegisterRequirementEndpointServer(s *grpc.Server, srv RequirementEndpointServer) {
	s.RegisterService(&_RequirementEndpoint_serviceDesc, srv)
}

func _RequirementEndpoint_GetRequirement_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequirementId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RequirementEndpointServer).GetRequirement(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/leveler.RequirementEndpoint/GetRequirement",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RequirementEndpointServer).GetRequirement(ctx, req.(*RequirementId))
	}
	return interceptor(ctx, in, info, handler)
}

func _RequirementEndpoint_ListRequirements_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Query)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RequirementEndpointServer).ListRequirements(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/leveler.RequirementEndpoint/ListRequirements",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RequirementEndpointServer).ListRequirements(ctx, req.(*Query))
	}
	return interceptor(ctx, in, info, handler)
}

func _RequirementEndpoint_CreateRequirement_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Requirement)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RequirementEndpointServer).CreateRequirement(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/leveler.RequirementEndpoint/CreateRequirement",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RequirementEndpointServer).CreateRequirement(ctx, req.(*Requirement))
	}
	return interceptor(ctx, in, info, handler)
}

func _RequirementEndpoint_UpdateRequirement_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Requirement)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RequirementEndpointServer).UpdateRequirement(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/leveler.RequirementEndpoint/UpdateRequirement",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RequirementEndpointServer).UpdateRequirement(ctx, req.(*Requirement))
	}
	return interceptor(ctx, in, info, handler)
}

func _RequirementEndpoint_DeleteRequirement_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequirementId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RequirementEndpointServer).DeleteRequirement(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/leveler.RequirementEndpoint/DeleteRequirement",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RequirementEndpointServer).DeleteRequirement(ctx, req.(*RequirementId))
	}
	return interceptor(ctx, in, info, handler)
}

var _RequirementEndpoint_serviceDesc = grpc.ServiceDesc{
	ServiceName: "leveler.RequirementEndpoint",
	HandlerType: (*RequirementEndpointServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetRequirement",
			Handler:    _RequirementEndpoint_GetRequirement_Handler,
		},
		{
			MethodName: "ListRequirements",
			Handler:    _RequirementEndpoint_ListRequirements_Handler,
		},
		{
			MethodName: "CreateRequirement",
			Handler:    _RequirementEndpoint_CreateRequirement_Handler,
		},
		{
			MethodName: "UpdateRequirement",
			Handler:    _RequirementEndpoint_UpdateRequirement_Handler,
		},
		{
			MethodName: "DeleteRequirement",
			Handler:    _RequirementEndpoint_DeleteRequirement_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "requirement.proto",
}

func init() { proto.RegisterFile("requirement.proto", fileDescriptor4) }

var fileDescriptor4 = []byte{
	// 425 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x53, 0x51, 0x6b, 0xdb, 0x30,
	0x10, 0x4e, 0x9c, 0xa6, 0x61, 0xe7, 0x2d, 0x4d, 0xae, 0xa5, 0x08, 0xef, 0x61, 0xc1, 0x50, 0xe8,
	0x5e, 0x54, 0xe8, 0x18, 0x8c, 0x3d, 0x94, 0x85, 0xd4, 0x94, 0xc0, 0x18, 0xcc, 0x6c, 0x3f, 0xc0,
	0x8d, 0x6f, 0x45, 0xcc, 0x91, 0x3c, 0x49, 0x0e, 0xe4, 0x07, 0x6f, 0xbf, 0x63, 0x58, 0x8e, 0x53,
	0x2d, 0x38, 0xb0, 0xb7, 0xd3, 0xf7, 0x7d, 0x77, 0xf7, 0xdd, 0x89, 0x83, 0xa9, 0xa6, 0x5f, 0x95,
	0xd0, 0xb4, 0x26, 0x69, 0x79, 0xa9, 0x95, 0x55, 0x38, 0x2a, 0x68, 0x43, 0x05, 0xe9, 0xe8, 0x65,
	0xb6, 0xb2, 0x42, 0xc9, 0x06, 0x8e, 0x26, 0x2b, 0x25, 0x8d, 0xd5, 0x99, 0x68, 0x85, 0x11, 0x54,
	0x56, 0x14, 0xbb, 0xf8, 0xf5, 0x93, 0x52, 0x4f, 0x05, 0xdd, 0xb8, 0xd7, 0x63, 0xf5, 0xe3, 0x86,
	0xd6, 0xa5, 0xdd, 0x36, 0x64, 0xfc, 0x06, 0x5e, 0xa5, 0xcf, 0x6d, 0x96, 0x39, 0x8e, 0x21, 0x58,
	0xe6, 0xac, 0x3f, 0xeb, 0x5f, 0xbf, 0x48, 0x83, 0x65, 0x1e, 0xff, 0x0e, 0x20, 0xf4, 0x14, 0x87,
	0x3c, 0x22, 0x9c, 0x7c, 0xc9, 0xd6, 0xc4, 0x02, 0x87, 0xb8, 0x18, 0x67, 0x10, 0xde, 0x93, 0x59,
	0x69, 0x51, 0xd6, 0x26, 0xd9, 0xc0, 0x51, 0x3e, 0x84, 0x6f, 0x61, 0x34, 0x77, 0x13, 0x18, 0x76,
	0x32, 0x1b, 0x5c, 0x87, 0xb7, 0x67, 0x7c, 0x37, 0x1a, 0x6f, 0xf0, 0xb4, 0xe5, 0xf1, 0x0a, 0x86,
	0xdf, 0xc8, 0x58, 0xc3, 0x86, 0xdd, 0xc2, 0x86, 0xc5, 0xf7, 0x10, 0x2e, 0xf6, 0x5b, 0x30, 0xec,
	0xd4, 0x89, 0xcf, 0xf7, 0xe2, 0x67, 0x2e, 0xf5, 0x75, 0xf8, 0x00, 0x61, 0x22, 0x37, 0x42, 0x2b,
	0x59, 0x4f, 0xc7, 0x46, 0x2e, 0xed, 0x6a, 0x9f, 0xe6, 0x4d, 0xce, 0x3d, 0x5d, 0x22, 0xad, 0xde,
	0xa6, 0x7e, 0x66, 0x74, 0x07, 0x93, 0x43, 0x01, 0x4e, 0x60, 0xf0, 0x93, 0xb6, 0xbb, 0x65, 0xd5,
	0x21, 0x5e, 0xc0, 0x70, 0x93, 0x15, 0x55, 0xbb, 0xae, 0xe6, 0xf1, 0x31, 0xf8, 0xd0, 0x8f, 0xe7,
	0x70, 0xe6, 0x35, 0xfb, 0x2c, 0x8c, 0x45, 0x0e, 0xa3, 0x94, 0x4c, 0x55, 0x58, 0xc3, 0xfa, 0xce,
	0xd7, 0x45, 0x97, 0xaf, 0xb4, 0x15, 0xdd, 0xfe, 0x09, 0xe0, 0xdc, 0x23, 0x12, 0x99, 0x97, 0x4a,
	0x48, 0x8b, 0x9f, 0x60, 0xfc, 0x40, 0xd6, 0xff, 0xc4, 0xcb, 0xae, 0x42, 0xcb, 0x3c, 0xea, 0x6c,
	0x10, 0xf7, 0xf0, 0x0e, 0x26, 0xb5, 0x23, 0x0f, 0x34, 0x38, 0xde, 0x6b, 0xbf, 0x56, 0xa4, 0xb7,
	0x11, 0xeb, 0xca, 0xad, 0xb3, 0xe2, 0x1e, 0x2e, 0x60, 0xba, 0xd0, 0x94, 0x59, 0xf2, 0x4d, 0x74,
	0x36, 0x8b, 0x8e, 0x58, 0x8b, 0x7b, 0x38, 0x87, 0xe9, 0xf7, 0x32, 0xff, 0xaf, 0x22, 0xc7, 0xe6,
	0x48, 0x60, 0x7a, 0x4f, 0x05, 0xfd, 0x5b, 0xe2, 0xd8, 0x32, 0x2e, 0x79, 0x73, 0x38, 0xbc, 0x3d,
	0x1c, 0x9e, 0xd4, 0x87, 0x13, 0xf7, 0x1e, 0x4f, 0x1d, 0xf2, 0xee, 0x6f, 0x00, 0x00, 0x00, 0xff,
	0xff, 0x34, 0x44, 0x6f, 0x58, 0xa2, 0x03, 0x00, 0x00,
}
